(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:23:08.697)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[2],[3],[1],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:24:13.677)
  (NBestInd 24)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[2],[],[1],[2],[2]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[2],[0],[0],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:24:23.262)
  (NBestInd 18)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[1],[3],[1],[0],[0],[1],[0]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:24:29.399)
  (NBestInd 0)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[1],[],[1],[0],[0],[1],[0]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[1],[0],[3],[3],[2],[0]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:24:36.731)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[1],[],[3],[3],[2],[]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[2],[2],[3],[3],[2]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:24:50.237)
  (NBestInd 24)
  (utterance "apagar vermelho")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 2 COLOR))))))
  (targetValue (string [[2],[2],[3],[3],[]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[0],[3],[3],[0],[0]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:25:12.765)
  (NBestInd 35)
  (utterance "acrescentar laranja direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getTopColor (number 0 COLOR))) (number 3 COLOR))))
  (targetValue (string [[0],[3],[3],[0],[0,3]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[2],[2],[0],[0],[0]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:25:23.208)
  (NBestInd 1)
  (utterance "acrescentar vermelho direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 2 COLOR))))
  (targetValue (string [[2],[2],[0],[0],[0,2]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[1],[3],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:25:29.029)
  (NBestInd 0)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[],[3],[],[]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[3],[3],[3],[2]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:25:37.077)
  (NBestInd 1)
  (utterance "acrescentar laranja")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 3 COLOR))))
  (targetValue (string [[3],[3],[3],[2,3]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[0],[0],[3],[0],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:25:54.470)
  (NBestInd 16)
  (utterance "acrescentar laranja em azul")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 0 COLOR)) (number 3 COLOR))))
  (targetValue (string [[0,3],[0,3],[3],[0,3],[3],[3]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[1],[1],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:26:03.461)
  (NBestInd 0)
  (utterance "acrescentar castanho em castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 1 COLOR))))
  (targetValue (string [[1,1],[1,1],[1,1],[1,1]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[3],[2],[2],[3],[2]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:26:18.899)
  (NBestInd 3)
  (utterance "acrescentar vermelho em laranja")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 3 COLOR)) (number 2 COLOR))))
  (targetValue (string [[3,2],[2],[2],[3,2],[2]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[2],[2],[3],[2],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:26:26.911)
  (NBestInd 1)
  (utterance "acrescentar laranja direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 3 COLOR))))
  (targetValue (string [[2],[2],[3],[2],[2],[2,3]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[0],[0],[3],[0],[3]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:26:35.779)
  (NBestInd 3)
  (utterance "apagar azul esquerda")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 0 COLOR))))))
  (targetValue (string [[],[0],[3],[0],[3]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[2,2],[2,3],[2,2],[2,3],[2,2]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:26:51.312)
  (NBestInd 0)
  (utterance "acrescentar laranja em vermelho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 3 COLOR)) (number 3 COLOR))))
  (targetValue (string [[2,2],[2,3,3],[2,2],[2,3,3],[2,2]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[2,2],[2,3],[2,2],[2,3],[2,2]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:27:03.403)
  (NBestInd 1)
  (utterance "acrescentar laranja em vermelho")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call context:getTopColor (number 3 COLOR))) (number 3 COLOR))))
  (targetValue (string [[2,2,3],[2,3],[2,2,3],[2,3],[2,2,3]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[3,3],[3,0],[3,3],[3,0]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:28:13.682)
  (NBestInd 1)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[3,3],[3],[3,3],[3]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[3,3],[3],[3,3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:28:23.119)
  (NBestInd 3)
  (utterance "acrescentar laranja")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call context:getTopColor (number 0 COLOR))) (number 3 COLOR))))
  (targetValue (string [[3,3,3],[3,3],[3,3,3],[3,3]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[2,2],[3,3],[2,2],[3,3]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:28:45.683)
  (NBestInd 1)
  (utterance "apagar laranja em laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[2,2],[3],[2,2],[3]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[2,2],[2,0],[2,2]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:28:52.861)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[2,2],[2],[2,2]]))
)
(example
  (id session:0GmuvkQbREL)
  (context (date 2018 5 5) (graph NaiveKnowledgeGraph ((string [[2,2],[2],[2,2]]) (name b) (name c))))
  (timeStamp 2018-06-05T11:29:03.024)
  (NBestInd 0)
  (utterance "acrescentar castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call context:getTopColor (number 1 COLOR))) (number 1 COLOR))))
  (targetValue (string [[2,2,1],[2,1],[2,2,1]]))
)
