(example
  (id session:2CgzahQeKWI)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[2],[3],[2],[2],[3],[1],[2]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:56:58.315)
  (NBestInd 7)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[2],[],[2],[2],[],[1],[2]]))
)
(example
  (id session:2CgzahQeKWI)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:57:02.773)
  (NBestInd 4)
  (utterance castanho)
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call leftMost1 (call context:getNonEmpty))) (number 1 COLOR))))
  (targetValue (string [[0],[1,1],[2,1],[3,1]]))
)
(example
  (id session:2CgzahQeKWI)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[3],[2],[1],[0],[2]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:58:22.989)
  (NBestInd 8)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[3],[2],[],[0],[2]]))
)
(example
  (id session:2CgzahQeKWI)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:58:26.253)
  (NBestInd 3)
  (utterance azul)
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getTopColor (number 3 COLOR))) (number 2 COLOR))))
  (targetValue (string [[0],[1],[2],[3,2]]))
)
(example
  (id session:2CgzahQeKWI)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[2],[1],[0],[2],[3],[0],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T10:26:34.950)
  (NBestInd 0)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[2],[1],[0],[2],[],[0],[]]))
)
(example
  (id session:2CgzahQeKWI)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T10:26:39.269)
  (NBestInd 6)
  (utterance vermelho)
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 0 COLOR))))))
  (targetValue (string [[],[1],[2],[3]]))
)
(example
  (id session:2CgzahQeKWI)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[3],[0],[3],[3],[0],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-06-15T10:27:49.734)
  (NBestInd 0)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[3],[0],[3],[3],[0],[],[]]))
)
(example
  (id session:2CgzahQeKWI)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T10:27:53.724)
  (NBestInd 8)
  (utterance azul)
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getTopColor (number 2 COLOR))) (number 3 COLOR))))
  (targetValue (string [[0],[1],[2,3],[3]]))
)
