(example
  (learningMode Implicit)
  (id session:2mmTlHZ7zng)
  (timeStamp 2018-10-12T16:54:51.466)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (learningMode Implicit)
  (id session:2mmTlHZ7zng)
  (timeStamp 2018-10-12T16:56:04.090)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (learningMode Implicit)
  (id session:2mmTlHZ7zng)
  (timeStamp 2018-10-12T16:57:18.293)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
