(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:38:23.322)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:38:29.365)
  (NBestInd 24)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[2],[],[1],[2],[2]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:38:37.807)
  (NBestInd 18)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
(example
  (learningMode Active)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:38:43.867)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[3],[2],[1],[1],[1],[1],[]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:39:01.304)
  (NBestInd 17)
  (utterance "adicionar laranja azul")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 0 COLOR)) (number 3 COLOR))))
  (targetValue (string [[0,3],[0,3],[3],[0,3],[3],[3]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:39:09.760)
  (NBestInd 0)
  (utterance "adicionar castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 1 COLOR))))
  (targetValue (string [[1,1],[1,1],[1,1],[1,1]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:39:33.577)
  (NBestInd 11)
  (utterance "adicionar vermelho laranja")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 3 COLOR)) (number 2 COLOR))))
  (targetValue (string [[3,2],[2],[2],[3,2],[2]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:39:53.742)
  (NBestInd 29)
  (utterance "adicionar laranja direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getTopColor (number 2 COLOR))) (number 3 COLOR))))
  (targetValue (string [[2],[2],[3],[2],[2],[2,3]]))
)
(example
  (learningMode Active)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:40:14.796)
  (NBestInd 36)
  (utterance "adicionar laranja")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getNonEmpty) (number 3 COLOR))))
  (targetValue (string [[3,3],[3,3],[2,3],[2,3],[1,3],[1,3]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:40:24.675)
  (NBestInd 18)
  (utterance "apagar esquerda")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 2 COLOR))))))
  (targetValue (string [[],[1],[2],[2]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:40:29.765)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[1,1],[0],[1,1],[0],[1,1],[0]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:40:40.372)
  (NBestInd 0)
  (utterance "adicionar castanho castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 1 COLOR))))
  (targetValue (string [[1,1,1],[0],[1,1,1],[0],[1,1,1],[0]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:40:46.551)
  (NBestInd 0)
  (utterance "apagar vermelho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[1,1],[2],[1,1],[2],[1,1],[2]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:40:55.125)
  (NBestInd 0)
  (utterance "adicionar castanho castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 1 COLOR))))
  (targetValue (string [[1,1,1],[2],[1,1,1],[2],[1,1,1],[2]]))
)
(example
  (learningMode Active)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:41:02.420)
  (NBestInd 1)
  (utterance "adicionar laranja direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 3 COLOR))))
  (targetValue (string [[3],[1],[3],[2],[0],[1,3]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:41:21.677)
  (NBestInd 4)
  (utterance "adicionar laranja castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 3 COLOR))))
  (targetValue (string [[0,1,3],[1,0],[0,1,3]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:41:36.732)
  (NBestInd 0)
  (utterance "apagar vermelho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[0],[2,0],[0],[2,0],[0],[2,0]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:41:41.884)
  (NBestInd 1)
  (utterance "adicionar azul")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 0 COLOR)) (number 0 COLOR))))
  (targetValue (string [[0,0],[2,0,0],[0,0],[2,0,0],[0,0],[2,0,0]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:41:55.011)
  (NBestInd 0)
  (utterance "adicionar vermelho vermelho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 2 COLOR)) (number 2 COLOR))))
  (targetValue (string [[2,3],[3,2,2],[2,3]]))
)
(example
  (learningMode Active)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:41:59.187)
  (NBestInd 0)
  (utterance "adicionar laranja castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 3 COLOR))))
  (targetValue (string [[0],[2],[0],[0],[1,3],[0]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:42:05.010)
  (NBestInd 0)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[3],[],[]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:42:31.452)
  (NBestInd 4)
  (utterance "adicionar azul direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 0 COLOR))))
  (targetValue (string [[0,2],[2,2,0]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:42:58.225)
  (NBestInd 10)
  (utterance "adicionar vermelho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getNonEmpty) (number 2 COLOR))))
  (targetValue (string [[2,2],[2,2,2],[3,0,2],[0,0,2]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:43:02.602)
  (NBestInd 0)
  (utterance "apagar direita")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getNonEmpty)))))
  (targetValue (string [[2,2],[2,2,2],[3,0,2],[0,0]]))
)
(example
  (learningMode Active)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:43:05.478)
  (NBestInd 0)
  (utterance "adicionar vermelho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getNonEmpty) (number 2 COLOR))))
  (targetValue (string [[0,2],[2,2],[0,2],[0,2],[0,2],[0,2]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:43:22.820)
  (NBestInd 0)
  (utterance "apagar vermelho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[],[3,0]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:43:28.493)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[],[3]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:43:35.774)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[],[2],[1,2],[0]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:43:49.383)
  (NBestInd 7)
  (utterance "adicionar vermelho vermelho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 2 COLOR)) (number 2 COLOR))))
  (targetValue (string [[0,0],[0,2,2,2],[0,2,2,2],[0,2,2],[0,0]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:43:55.997)
  (NBestInd 1)
  (utterance "apagar vermelho esquerda")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 2 COLOR))))))
  (targetValue (string [[0,0],[0,2,2],[0,2,2,2],[0,2,2],[0,0]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:44:03.301)
  (NBestInd 1)
  (utterance "adicionar azul")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getNonEmpty) (number 0 COLOR))))
  (targetValue (string [[0,0,0],[0,2,2,0],[0,2,2,2,0],[0,2,2,0],[0,0,0]]))
)
(example
  (learningMode Active)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:44:07.769)
  (NBestInd 0)
  (utterance "adicionar laranja azul")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 0 COLOR)) (number 3 COLOR))))
  (targetValue (string [[2],[0,3],[3],[1],[2],[3],[2]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:44:22.317)
  (NBestInd 7)
  (utterance "adicionar vermelho esquerda")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call rightMost1 (call context:getNonEmpty))) (number 2 COLOR))))
  (targetValue (string [[1,2],[1,2],[1,2],[1]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:44:40.880)
  (NBestInd 2)
  (utterance "adicionar azul vermelho")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call rightMost1 (call context:getNonEmpty))) (number 0 COLOR))))
  (targetValue (string [[1,2,0],[1,2,0],[1,2,0],[1]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:44:49.770)
  (NBestInd 3)
  (utterance "apagar azul direita")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 0 COLOR))))))
  (targetValue (string [[1,2,0],[1,2,0],[1,2],[1]]))
)
(example
  (learningMode Implicit)
  (id session:3jrAss19tin)
  (timeStamp 2018-10-05T14:44:59.855)
  (NBestInd 14)
  (utterance "adicionar laranja esquerda")
  (targetFormula (call wallToString (call context:stackOnTop (call leftMost1 (call context:getNonEmpty)) (number 3 COLOR))))
  (targetValue (string [[1,2,0,3],[1,2,0],[1,2],[1]]))
)
