(example
  (id session:6tHZugqSq5F)
  (context (date 2018 5 28) (graph NaiveKnowledgeGraph ((string [[1],[2],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-28T13:28:46.196)
  (NBestInd 6)
  (utterance "apagar vermelho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[1],[],[1],[],[3]]))
)
(example
  (id session:6tHZugqSq5F)
  (context (date 2018 5 28) (graph NaiveKnowledgeGraph ((string [[1],[3],[2],[0],[0]]) (name b) (name c))))
  (timeStamp 2018-06-28T13:28:52.795)
  (NBestInd 14)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[],[3],[2],[0],[0]]))
)
(example
  (id session:6tHZugqSq5F)
  (context (date 2018 5 28) (graph NaiveKnowledgeGraph ((string [[3],[2],[1],[1],[0]]) (name b) (name c))))
  (timeStamp 2018-06-28T13:28:59.025)
  (NBestInd 8)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[2],[1],[1],[0]]))
)
