(example
  (learningMode Implicit)
  (id session:7xxlE8ulMXj)
  (timeStamp 2018-09-13T16:04:09.902)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (learningMode Implicit)
  (id session:7xxlE8ulMXj)
  (timeStamp 2018-09-13T16:04:15.874)
  (NBestInd 24)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[2],[],[1],[2],[2]]))
)
(example
  (learningMode Implicit)
  (id session:7xxlE8ulMXj)
  (timeStamp 2018-09-13T16:04:23.652)
  (NBestInd 18)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
