(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T14:52:31.076)
  (NBestInd 2)
  (utterance "apagar bloco azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T14:52:48.035)
  (NBestInd 24)
  (utterance "apagar bloco laranja")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[2],[],[1],[2],[2]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T14:53:07.299)
  (NBestInd 17)
  (utterance "apagar blocos castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
(example
  (learningMode Active)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T14:53:11.640)
  (NBestInd 0)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[],[2],[1],[1],[1],[1],[0]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T14:54:04.117)
  (NBestInd 42)
  (utterance "adicionar blocos laranja em azul")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 0 COLOR)) (number 3 COLOR))))
  (targetValue (string [[0,3],[0,3],[3],[0,3],[3],[3]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T14:54:14.157)
  (NBestInd 0)
  (utterance "adicionar blocos castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 1 COLOR))))
  (targetValue (string [[1,1],[1,1],[1,1],[1,1]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T14:54:28.168)
  (NBestInd 13)
  (utterance "adicionar blocos vermelho laranja")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 3 COLOR)) (number 2 COLOR))))
  (targetValue (string [[3,2],[2],[2],[3,2],[2]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T14:55:36.869)
  (NBestInd 22)
  (utterance "adicionar bloco laranja direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getTopColor (number 2 COLOR))) (number 3 COLOR))))
  (targetValue (string [[2],[2],[3],[2],[2],[2,3]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T14:56:19.066)
  (NBestInd 2)
  (utterance "apagar bloco esquerda")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[1],[2],[2]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T14:56:31.429)
  (NBestInd 0)
  (utterance "apagar blocos azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[1,1],[0],[1,1],[0],[1,1],[0]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T14:56:40.461)
  (NBestInd 0)
  (utterance "adicionar blocos castanho em castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 1 COLOR))))
  (targetValue (string [[1,1,1],[0],[1,1,1],[0],[1,1,1],[0]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T14:56:47.869)
  (NBestInd 0)
  (utterance "apagar blocos vermelho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[1,1],[2],[1,1],[2],[1,1],[2]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T14:56:56.693)
  (NBestInd 0)
  (utterance "adicionar blocos castanho em castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 1 COLOR))))
  (targetValue (string [[1,1,1],[2],[1,1,1],[2],[1,1,1],[2]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T14:58:27.998)
  (NBestInd 9)
  (utterance "adicionar blocos laranja em castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call context:getTopColor (number 0 COLOR))) (number 3 COLOR))))
  (targetValue (string [[0,1,3],[1,0],[0,1,3]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T14:58:59.989)
  (NBestInd 0)
  (utterance "apagar blocos vermelho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[0],[2,0],[0],[2,0],[0],[2,0]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T14:59:18.078)
  (NBestInd 1)
  (utterance "adicionar blocos azul em azul")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 0 COLOR)) (number 0 COLOR))))
  (targetValue (string [[0,0],[2,0,0],[0,0],[2,0,0],[0,0],[2,0,0]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T14:59:35.961)
  (NBestInd 0)
  (utterance "adicionar bloco vermelho em vermelho")
  (targetFormula (call wallToString (call context:stackOnTop (call leftMost1 (call context:getTopColor (number 2 COLOR))) (number 2 COLOR))))
  (targetValue (string [[2,3],[3,2,2],[2,3]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T15:00:07.755)
  (NBestInd 0)
  (utterance "apagar blocos castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[3],[],[]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T15:00:28.364)
  (NBestInd 4)
  (utterance "adiconar bloco azul direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getTopColor (number 2 COLOR))) (number 0 COLOR))))
  (targetValue (string [[0,2],[2,2,0]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T15:01:23.265)
  (NBestInd 27)
  (utterance "adicionar blocos vermelho")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call context:getTopColor (number 1 COLOR))) (number 2 COLOR))))
  (targetValue (string [[2,2],[2,2,2],[3,0,2],[0,0,2]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T15:01:36.011)
  (NBestInd 2)
  (utterance "apagar bloco direita")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 2 COLOR))))))
  (targetValue (string [[2,2],[2,2,2],[3,0,2],[0,0]]))
)
(example
  (learningMode Active)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T15:01:44.909)
  (NBestInd 2)
  (utterance "adicionar vermelho em")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call context:getTopColor (number 0 COLOR))) (number 2 COLOR))))
  (targetValue (string [[2,2],[2,2],[3,2],[2,2],[2,2],[3,2]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T15:02:02.599)
  (NBestInd 3)
  (utterance "apagar blocos")
  (targetFormula (call wallToString (call context:removeTop (call complement (call context:getTopColor (number 1 COLOR))))))
  (targetValue (string [[],[3]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T15:02:12.325)
  (NBestInd 0)
  (utterance "apagar blocos azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[],[2],[1,2],[0]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T15:02:40.426)
  (NBestInd 4)
  (utterance "adicionar blocos vermelho em vermelho")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call context:getTopColor (number 0 COLOR))) (number 2 COLOR))))
  (targetValue (string [[0,0],[0,2,2,2],[0,2,2,2],[0,2,2],[0,0]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T15:02:51.145)
  (NBestInd 0)
  (utterance "apagar bloco vermelho esquerda")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 2 COLOR))))))
  (targetValue (string [[0,0],[0,2,2],[0,2,2,2],[0,2,2],[0,0]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T15:03:14.084)
  (NBestInd 18)
  (utterance "adicionar blocos azul")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call context:getTopColor (number 1 COLOR))) (number 0 COLOR))))
  (targetValue (string [[0,0,0],[0,2,2,0],[0,2,2,2,0],[0,2,2,0],[0,0,0]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T15:03:27.191)
  (NBestInd 20)
  (utterance "adicionar blocos vermelho esquerda")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call rightMost1 (call context:getNonEmpty))) (number 2 COLOR))))
  (targetValue (string [[1,2],[1,2],[1,2],[1]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T15:03:37.968)
  (NBestInd 8)
  (utterance "adicionar blocos azul em vermelho")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call context:getTopColor (number 1 COLOR))) (number 0 COLOR))))
  (targetValue (string [[1,2,0],[1,2,0],[1,2,0],[1]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T15:04:01.094)
  (NBestInd 11)
  (utterance "apagar bloco azul direita")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 0 COLOR))))))
  (targetValue (string [[1,2,0],[1,2,0],[1,2],[1]]))
)
(example
  (learningMode Implicit)
  (id session:BombnXquLW4)
  (timeStamp 2018-10-05T15:04:24.864)
  (NBestInd 38)
  (utterance "adicionar bloco laranja esquerda")
  (targetFormula (call wallToString (call context:stackOnTop (call leftMost1 (call context:getNonEmpty)) (number 3 COLOR))))
  (targetValue (string [[1,2,0,3],[1,2,0],[1,2],[1]]))
)
