(example
  (id session:bVuQHNoN9V8)
  (context (date 2018 5 16) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-16T11:33:51.401)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:bVuQHNoN9V8)
  (context (date 2018 5 16) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-16T11:33:58.445)
  (NBestInd 15)
  (utterance apagar)
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getNonEmpty)))))
  (targetValue (string [[0],[1],[2],[]]))
)
(example
  (id session:bVuQHNoN9V8)
  (context (date 2018 5 16) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-16T11:35:14.886)
  (NBestInd 2)
  (utterance azul)
  (targetFormula (call wallToString (call context:stackOnTop (call leftMost1 (call context:getTopColor (number 0 COLOR))) (number 0 COLOR))))
  (targetValue (string [[0,0],[1],[2],[3]]))
)
(example
  (id session:bVuQHNoN9V8)
  (context (date 2018 5 16) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-16T11:35:35.397)
  (NBestInd 7)
  (utterance apagar)
  (targetFormula (call wallToString (call context:removeTop (call complement (call rightMost1 (call context:getTopColor (number 3 COLOR)))))))
  (targetValue (string [[],[],[],[3]]))
)
(example
  (id session:bVuQHNoN9V8)
  (context (date 2018 5 16) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-16T11:38:55.086)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:bVuQHNoN9V8)
  (context (date 2018 5 16) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-16T11:38:59.164)
  (NBestInd 2)
  (utterance apagar)
  (targetFormula (call wallToString (call context:stackOnTop (call leftMost1 (call context:getTopColor (number 0 COLOR))) (number 0 COLOR))))
  (targetValue (string [[0,0],[1],[2],[3]]))
)
