(example
  (id session:DizIlizLGOW)
  (context (date 2018 5 6) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-06T13:12:11.387)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:DizIlizLGOW)
  (context (date 2018 5 6) (graph NaiveKnowledgeGraph ((string [[2],[3],[1],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-06-06T13:12:18.263)
  (NBestInd 24)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[2],[],[1],[2],[2]]))
)
(example
  (id session:DizIlizLGOW)
  (context (date 2018 5 6) (graph NaiveKnowledgeGraph ((string [[2],[0],[0],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-06-06T13:12:26.162)
  (NBestInd 18)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
(example
  (id session:DizIlizLGOW)
  (context (date 2018 5 6) (graph NaiveKnowledgeGraph ((string [[1],[3],[1],[0],[0],[1],[0]]) (name b) (name c))))
  (timeStamp 2018-06-06T13:12:38.405)
  (NBestInd 0)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[1],[],[1],[0],[0],[1],[0]]))
)
(example
  (id session:DizIlizLGOW)
  (context (date 2018 5 6) (graph NaiveKnowledgeGraph ((string [[1],[0],[3],[3],[2],[0]]) (name b) (name c))))
  (timeStamp 2018-06-06T13:12:43.129)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[1],[],[3],[3],[2],[]]))
)
(example
  (id session:DizIlizLGOW)
  (context (date 2018 5 6) (graph NaiveKnowledgeGraph ((string [[2],[2],[3],[3],[2]]) (name b) (name c))))
  (timeStamp 2018-06-06T13:12:54.857)
  (NBestInd 24)
  (utterance "apagar direita")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 2 COLOR))))))
  (targetValue (string [[2],[2],[3],[3],[]]))
)
(example
  (id session:DizIlizLGOW)
  (context (date 2018 5 6) (graph NaiveKnowledgeGraph ((string [[0],[3],[3],[0],[0]]) (name b) (name c))))
  (timeStamp 2018-06-06T13:13:04.682)
  (NBestInd 13)
  (utterance "acrescentar laranja direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 3 COLOR))))
  (targetValue (string [[0],[3],[3],[0],[0,3]]))
)
(example
  (id session:DizIlizLGOW)
  (context (date 2018 5 6) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-06T13:13:17.511)
  (NBestInd 0)
  (utterance esquerda)
)
(example
  (id session:DizIlizLGOW)
  (context (date 2018 5 6) (graph NaiveKnowledgeGraph ((string [[0],[3],[3],[0],[3],[0]]) (name b) (name c))))
  (timeStamp 2018-06-06T13:18:41.204)
  (NBestInd 1)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[0],[],[],[0],[],[0]]))
)
(example
  (id session:DizIlizLGOW)
  (context (date 2018 5 6) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-06T13:19:17.775)
  (NBestInd 0)
  (utterance esquerda)
)
(example
  (id session:DizIlizLGOW)
  (context (date 2018 5 6) (graph NaiveKnowledgeGraph ((string [[2],[1],[2],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-06-06T13:19:58.316)
  (NBestInd 1)
  (utterance "acrescentar vermelho direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 2 COLOR))))
  (targetValue (string [[2],[1],[2],[2],[2,2]]))
)
(example
  (id session:DizIlizLGOW)
  (context (date 2018 5 6) (graph NaiveKnowledgeGraph ((string [[0],[0],[0],[0],[0]]) (name b) (name c))))
  (timeStamp 2018-06-06T13:20:50.941)
  (NBestInd 0)
  (utterance "apagar direita")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getNonEmpty)))))
  (targetValue (string [[0],[0],[0],[0],[]]))
)
(example
  (id session:DizIlizLGOW)
  (context (date 2018 5 6) (graph NaiveKnowledgeGraph ((string [[1],[1],[1],[1],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-06-06T13:27:56.172)
  (NBestInd 12)
  (utterance "acrescentar vermelho direita")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 2 COLOR)) (number 2 COLOR))))
  (targetValue (string [[1],[1],[1],[1],[2,2],[2,2]]))
)
(example
  (id session:DizIlizLGOW)
  (context (date 2018 5 6) (graph NaiveKnowledgeGraph ((string [[2],[1],[1],[1],[2],[1]]) (name b) (name c))))
  (timeStamp 2018-06-06T13:28:26.189)
  (NBestInd 0)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[],[],[],[2],[]]))
)
(example
  (id session:DizIlizLGOW)
  (context (date 2018 5 6) (graph NaiveKnowledgeGraph ((string [[1],[3],[1],[3],[1],[3]]) (name b) (name c))))
  (timeStamp 2018-06-06T13:28:33.475)
  (NBestInd 0)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[1],[],[1],[],[1],[]]))
)
(example
  (id session:DizIlizLGOW)
  (context (date 2018 5 6) (graph NaiveKnowledgeGraph ((string [[3],[1],[1],[3]]) (name b) (name c))))
  (timeStamp 2018-06-06T13:28:44.308)
  (NBestInd 6)
  (utterance "acrescentar laranja em castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 3 COLOR))))
  (targetValue (string [[3],[1,3],[1,3],[3]]))
)
(example
  (id session:DizIlizLGOW)
  (context (date 2018 5 6) (graph NaiveKnowledgeGraph ((string [[1],[1],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-06-06T13:29:05.903)
  (NBestInd 1)
  (utterance "acrescentar laranja direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 3 COLOR))))
  (targetValue (string [[1],[1],[1],[1,3]]))
)
