(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:33:44.877)
  (NBestInd 2)
  (utterance "apagar bloco azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:33:51.890)
  (NBestInd 24)
  (utterance "apagar bloco laranja")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[2],[],[1],[2],[2]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:34:03.584)
  (NBestInd 17)
  (utterance "apagar blocos castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
(example
  (learningMode Active)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:34:09.340)
  (NBestInd 0)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[],[2],[1],[1],[1],[1],[0]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:34:24.379)
  (NBestInd 42)
  (utterance "adicionar blocos laranja azul")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 0 COLOR)) (number 3 COLOR))))
  (targetValue (string [[0,3],[0,3],[3],[0,3],[3],[3]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:34:35.701)
  (NBestInd 0)
  (utterance "adicionar blocos castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 1 COLOR))))
  (targetValue (string [[1,1],[1,1],[1,1],[1,1]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:34:50.748)
  (NBestInd 13)
  (utterance "adicionar blocos vermelho em laranja")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 3 COLOR)) (number 2 COLOR))))
  (targetValue (string [[3,2],[2],[2],[3,2],[2]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:35:06.452)
  (NBestInd 22)
  (utterance "adicionar bloco laranja direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getTopColor (number 2 COLOR))) (number 3 COLOR))))
  (targetValue (string [[2],[2],[3],[2],[2],[2,3]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:35:56.576)
  (NBestInd 2)
  (utterance "apagar bloco esquerda")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[1],[2],[2]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:36:06.599)
  (NBestInd 0)
  (utterance "apagar blocos azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[1,1],[0],[1,1],[0],[1,1],[0]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:36:14.341)
  (NBestInd 0)
  (utterance "adicionar blocos castanho castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 1 COLOR))))
  (targetValue (string [[1,1,1],[0],[1,1,1],[0],[1,1,1],[0]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:36:21.652)
  (NBestInd 0)
  (utterance "apagar blocos vermelho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[1,1],[2],[1,1],[2],[1,1],[2]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:36:27.641)
  (NBestInd 0)
  (utterance "adicionar blocos castanho castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 1 COLOR))))
  (targetValue (string [[1,1,1],[2],[1,1,1],[2],[1,1,1],[2]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:37:28.648)
  (NBestInd 12)
  (utterance "adicionar blocos laranja castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 3 COLOR))))
  (targetValue (string [[0,1,3],[1,0],[0,1,3]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:37:43.359)
  (NBestInd 0)
  (utterance "apagar blocos vermelho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[0],[2,0],[0],[2,0],[0],[2,0]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:37:50.180)
  (NBestInd 3)
  (utterance "adicionar blocos azul")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 0 COLOR)) (number 0 COLOR))))
  (targetValue (string [[0,0],[2,0,0],[0,0],[2,0,0],[0,0],[2,0,0]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:38:02.126)
  (NBestInd 0)
  (utterance "adicionar bloco vermelho vermelho")
  (targetFormula (call wallToString (call context:stackOnTop (call leftMost1 (call context:getTopColor (number 2 COLOR))) (number 2 COLOR))))
  (targetValue (string [[2,3],[3,2,2],[2,3]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:38:52.347)
  (NBestInd 0)
  (utterance "apagar blocos castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[3],[],[]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:39:03.523)
  (NBestInd 0)
  (utterance "adicionar bloco azul direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getTopColor (number 2 COLOR))) (number 0 COLOR))))
  (targetValue (string [[0,2],[2,2,0]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:39:36.105)
  (NBestInd 31)
  (utterance "adicionar blocos vermelho esquerda")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call rightMost1 (call context:getNonEmpty))) (number 2 COLOR))))
  (targetValue (string [[2,2],[2,2,2],[3,0,2],[0,0]]))
)
(example
  (learningMode Active)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:39:46.500)
  (NBestInd 9)
  (utterance "blocos vermelho laranja")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 3 COLOR)) (number 2 COLOR))))
  (targetValue (string [[2],[2],[3,2],[2],[2],[3,2]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:40:13.207)
  (NBestInd 5)
  (utterance "apagar blocos")
  (targetFormula (call wallToString (call context:removeTop (call complement (call context:getTopColor (number 1 COLOR))))))
  (targetValue (string [[],[3]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:40:22.492)
  (NBestInd 0)
  (utterance "apagar blocos azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[],[2],[1,2],[0]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:40:48.760)
  (NBestInd 13)
  (utterance "adicionar blocos vermelho vermelho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 2 COLOR)) (number 2 COLOR))))
  (targetValue (string [[0,0],[0,2,2,2],[0,2,2,2],[0,2,2],[0,0]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:40:56.934)
  (NBestInd 3)
  (utterance "apagar bloco vermelho esquerda")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 2 COLOR))))))
  (targetValue (string [[0,0],[0,2,2],[0,2,2,2],[0,2,2],[0,0]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:41:07.980)
  (NBestInd 17)
  (utterance "adicionar blocos azul")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call context:getTopColor (number 3 COLOR))) (number 0 COLOR))))
  (targetValue (string [[0,0,0],[0,2,2,0],[0,2,2,2,0],[0,2,2,0],[0,0,0]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:41:20.381)
  (NBestInd 3)
  (utterance "adicionar blocos vermelho esquerda")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call rightMost1 (call context:getNonEmpty))) (number 2 COLOR))))
  (targetValue (string [[1,2],[1,2],[1,2],[1]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:41:29.609)
  (NBestInd 2)
  (utterance "adicionar blocos azul vermelho")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call rightMost1 (call context:getNonEmpty))) (number 0 COLOR))))
  (targetValue (string [[1,2,0],[1,2,0],[1,2,0],[1]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:41:43.524)
  (NBestInd 19)
  (utterance "apagar bloco azul direita")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 0 COLOR))))))
  (targetValue (string [[1,2,0],[1,2,0],[1,2],[1]]))
)
(example
  (learningMode Implicit)
  (id session:dvf3CJCPOXp)
  (timeStamp 2018-10-06T10:41:56.945)
  (NBestInd 57)
  (utterance "adicionar bloco laranja esquerda")
  (targetFormula (call wallToString (call context:stackOnTop (call leftMost1 (call context:getNonEmpty)) (number 3 COLOR))))
  (targetValue (string [[1,2,0,3],[1,2,0],[1,2],[1]]))
)
