(example
  (id session:dW5cuOGZ7np)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T20:48:12.926)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:dW5cuOGZ7np)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T20:48:30.547)
  (NBestInd 13)
  (utterance apagar)
  (targetFormula (call wallToString (call context:removeTop (call context:getNonEmpty))))
  (targetValue (string [[],[],[],[]]))
)
