(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-07T08:33:44.626)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[2],[3],[1],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-06-07T08:33:54.895)
  (NBestInd 24)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[2],[],[1],[2],[2]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[2],[0],[0],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-06-07T08:34:02.509)
  (NBestInd 18)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[1],[3],[1],[0],[0],[1],[0]]) (name b) (name c))))
  (timeStamp 2018-06-07T08:34:08.874)
  (NBestInd 0)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[1],[],[1],[0],[0],[1],[0]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[1],[0],[3],[3],[2],[0]]) (name b) (name c))))
  (timeStamp 2018-06-07T08:34:15.745)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[1],[],[3],[3],[2],[]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[2],[2],[3],[3],[2]]) (name b) (name c))))
  (timeStamp 2018-06-07T08:34:29.003)
  (NBestInd 24)
  (utterance "apagar direita")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 2 COLOR))))))
  (targetValue (string [[2],[2],[3],[3],[]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[0],[3],[3],[0],[0]]) (name b) (name c))))
  (timeStamp 2018-06-07T08:34:46.119)
  (NBestInd 35)
  (utterance "acrescentar laranja esquerda")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getTopColor (number 0 COLOR))) (number 3 COLOR))))
  (targetValue (string [[0],[3],[3],[0],[0,3]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[2],[2],[0],[0],[0]]) (name b) (name c))))
  (timeStamp 2018-06-07T08:35:14.441)
  (NBestInd 0)
  (utterance "acrescentat vermelho direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 2 COLOR))))
  (targetValue (string [[2],[2],[0],[0],[0,2]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[1],[3],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-06-07T08:35:21.453)
  (NBestInd 0)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[],[3],[],[]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[3],[3],[3],[2]]) (name b) (name c))))
  (timeStamp 2018-06-07T08:41:48.469)
  (NBestInd 1)
  (utterance "acrescentar laranja direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 3 COLOR))))
  (targetValue (string [[3],[3],[3],[2,3]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[0],[0],[3],[0],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-07T08:42:00.700)
  (NBestInd 6)
  (utterance "acrescentar laranja em azul")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 0 COLOR)) (number 3 COLOR))))
  (targetValue (string [[0,3],[0,3],[3],[0,3],[3],[3]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[1],[1],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-06-07T08:42:12.424)
  (NBestInd 1)
  (utterance "acrescentar castanho em castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 1 COLOR))))
  (targetValue (string [[1,1],[1,1],[1,1],[1,1]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[3],[2],[2],[3],[2]]) (name b) (name c))))
  (timeStamp 2018-06-07T09:11:46.377)
  (NBestInd 20)
  (utterance "acrescentar vermelho em laranja")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 3 COLOR)) (number 2 COLOR))))
  (targetValue (string [[3,2],[2],[2],[3,2],[2]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[2],[2],[3],[2],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-06-07T09:12:00.206)
  (NBestInd 3)
  (utterance "acrescentar laranja direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 3 COLOR))))
  (targetValue (string [[2],[2],[3],[2],[2],[2,3]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[0],[0],[3],[0],[3]]) (name b) (name c))))
  (timeStamp 2018-06-07T09:12:11.498)
  (NBestInd 5)
  (utterance "apagar esquerda")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[0],[3],[0],[3]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[2,2],[2,3],[2,2],[2,3],[2,2]]) (name b) (name c))))
  (timeStamp 2018-06-07T09:12:33.716)
  (NBestInd 3)
  (utterance "acrescentar laranja em vermelho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 2 COLOR)) (number 3 COLOR))))
  (targetValue (string [[2,2,3],[2,3],[2,2,3],[2,3],[2,2,3]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[3,3],[3,0],[3,3],[3,0]]) (name b) (name c))))
  (timeStamp 2018-06-07T09:12:44.468)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[3,3],[3],[3,3],[3]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[3,3],[3],[3,3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-07T09:12:53.554)
  (NBestInd 2)
  (utterance "acrescentar laranja")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 3 COLOR)) (number 3 COLOR))))
  (targetValue (string [[3,3,3],[3,3],[3,3,3],[3,3]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[2,2],[3,3],[2,2],[3,3]]) (name b) (name c))))
  (timeStamp 2018-06-07T09:13:23.645)
  (NBestInd 0)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[2,2],[3],[2,2],[3]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[2,2],[2,0],[2,2]]) (name b) (name c))))
  (timeStamp 2018-06-07T09:13:36.535)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[2,2],[2],[2,2]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[2,2],[2],[2,2]]) (name b) (name c))))
  (timeStamp 2018-06-07T09:13:42.853)
  (NBestInd 0)
  (utterance "acrescentar castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call context:getTopColor (number 1 COLOR))) (number 1 COLOR))))
  (targetValue (string [[2,2,1],[2,1],[2,2,1]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[1,1],[1,2],[1,1],[1,2],[1,1]]) (name b) (name c))))
  (timeStamp 2018-06-07T09:19:01.223)
  (NBestInd 0)
  (utterance "acrecentar vermelho em castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 2 COLOR))))
  (targetValue (string [[1,1,2],[1,2],[1,1,2],[1,2],[1,1,2]]))
)
(example
  (id session:dwNeI1BPQsw)
  (context (date 2018 5 7) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-07T09:28:07.756)
  (NBestInd 0)
  (utterance esquerda)
)
