(example
  (id session:Ec5meaSMR8H)
  (context (date 2018 5 22) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-22T01:06:02.674)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:Ec5meaSMR8H)
  (context (date 2018 5 22) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-22T01:10:36.610)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:Ec5meaSMR8H)
  (context (date 2018 5 22) (graph NaiveKnowledgeGraph ((string [[2],[3],[1],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-06-22T01:10:51.861)
  (NBestInd 24)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[2],[],[1],[2],[2]]))
)
(example
  (id session:Ec5meaSMR8H)
  (context (date 2018 5 22) (graph NaiveKnowledgeGraph ((string [[2],[0],[0],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-06-22T01:11:08.279)
  (NBestInd 18)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
(example
  (id session:Ec5meaSMR8H)
  (context (date 2018 5 22) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-22T01:14:31.022)
  (NBestInd 0)
  (utterance azul)
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[1],[2],[3]]))
)
(example
  (id session:Ec5meaSMR8H)
  (context (date 2018 5 22) (graph NaiveKnowledgeGraph ((string [[3],[0],[1],[0],[3],[1]]) (name b) (name c))))
  (timeStamp 2018-06-22T01:14:37.364)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[3],[],[1],[],[3],[1]]))
)
(example
  (id session:Ec5meaSMR8H)
  (context (date 2018 5 22) (graph NaiveKnowledgeGraph ((string [[3],[1],[3],[1],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-06-22T01:14:49.060)
  (NBestInd 0)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[],[1],[],[1],[1],[1]]))
)
(example
  (id session:Ec5meaSMR8H)
  (context (date 2018 5 22) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-22T01:14:59.135)
  (NBestInd 6)
  (utterance castanho)
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 1 COLOR))))))
  (targetValue (string [[0],[],[2],[3]]))
)
(example
  (id session:Ec5meaSMR8H)
  (context (date 2018 5 22) (graph NaiveKnowledgeGraph ((string [[2],[0],[2],[0]]) (name b) (name c))))
  (timeStamp 2018-06-22T01:15:14.722)
  (NBestInd 15)
  (utterance "adicionar azul esquerda")
  (targetFormula (call wallToString (call context:stackOnTop (call leftMost1 (call context:getNonEmpty)) (number 0 COLOR))))
  (targetValue (string [[2,0],[0],[2],[0]]))
)
(example
  (id session:Ec5meaSMR8H)
  (context (date 2018 5 22) (graph NaiveKnowledgeGraph ((string [[1],[0],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-06-22T01:15:23.509)
  (NBestInd 2)
  (utterance "apagar castanho esquerda")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 1 COLOR))))))
  (targetValue (string [[],[0],[1],[1]]))
)
