(example
  (id session:EM0YoSkXrue)
  (context (date 2018 2 19) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-19T11:33:00.768)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:EM0YoSkXrue)
  (context (date 2018 2 19) (graph NaiveKnowledgeGraph ((string [[2],[3],[1],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-03-19T11:33:13.965)
  (NBestInd 24)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[2],[],[1],[2],[2]]))
)
(example
  (id session:EM0YoSkXrue)
  (context (date 2018 2 19) (graph NaiveKnowledgeGraph ((string [[2],[0],[0],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-03-19T11:33:32.553)
  (NBestInd 18)
  (utterance "apagar castanhos")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
(example
  (id session:EM0YoSkXrue)
  (context (date 2018 2 19) (graph NaiveKnowledgeGraph ((string [[1],[3],[1],[0],[0],[1],[0]]) (name b) (name c))))
  (timeStamp 2018-03-19T11:33:42.735)
  (NBestInd 0)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[1],[],[1],[0],[0],[1],[0]]))
)
(example
  (id session:EM0YoSkXrue)
  (context (date 2018 2 19) (graph NaiveKnowledgeGraph ((string [[1],[0],[3],[3],[2],[0]]) (name b) (name c))))
  (timeStamp 2018-03-19T11:33:50.429)
  (NBestInd 0)
  (utterance "apagar azuis")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[1],[],[3],[3],[2],[]]))
)
(example
  (id session:EM0YoSkXrue)
  (context (date 2018 2 19) (graph NaiveKnowledgeGraph ((string [[2],[2],[3],[3],[2]]) (name b) (name c))))
  (timeStamp 2018-03-19T11:34:21.780)
  (NBestInd 24)
  (utterance "apagar vermelho")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 2 COLOR))))))
  (targetValue (string [[2],[2],[3],[3],[]]))
)
(example
  (id session:EM0YoSkXrue)
  (context (date 2018 2 19) (graph NaiveKnowledgeGraph ((string [[0],[3],[3],[0],[0]]) (name b) (name c))))
  (timeStamp 2018-03-19T11:34:52.427)
  (NBestInd 35)
  (utterance "acrescentar laranja lado direito")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getTopColor (number 0 COLOR))) (number 3 COLOR))))
  (targetValue (string [[0],[3],[3],[0],[0,3]]))
)
(example
  (id session:EM0YoSkXrue)
  (context (date 2018 2 19) (graph NaiveKnowledgeGraph ((string [[2],[2],[0],[0],[0]]) (name b) (name c))))
  (timeStamp 2018-03-19T11:35:09.088)
  (NBestInd 2)
  (utterance "acrescentar vermelho lado direito")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 2 COLOR))))
  (targetValue (string [[2],[2],[0],[0],[0,2]]))
)
(example
  (id session:EM0YoSkXrue)
  (context (date 2018 2 19) (graph NaiveKnowledgeGraph ((string [[1],[3],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-03-19T11:35:25.830)
  (NBestInd 15)
  (utterance "remover castanhos")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[],[3],[],[]]))
)
(example
  (id session:EM0YoSkXrue)
  (context (date 2018 2 19) (graph NaiveKnowledgeGraph ((string [[3],[3],[3],[2]]) (name b) (name c))))
  (timeStamp 2018-03-19T11:35:40.091)
  (NBestInd 1)
  (utterance "acrescentar laranja lado direito")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 3 COLOR))))
  (targetValue (string [[3],[3],[3],[2,3]]))
)
(example
  (id session:EM0YoSkXrue)
  (context (date 2018 2 19) (graph NaiveKnowledgeGraph ((string [[0],[0],[3],[0],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-19T11:36:20.197)
  (NBestInd 9)
  (utterance "acrescentar laranja em cima azuis")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 0 COLOR)) (number 3 COLOR))))
  (targetValue (string [[0,3],[0,3],[3],[0,3],[3],[3]]))
)
(example
  (id session:EM0YoSkXrue)
  (context (date 2018 2 19) (graph NaiveKnowledgeGraph ((string [[1],[1],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-03-19T11:36:31.881)
  (NBestInd 31)
  (utterance "acrescentar castanho todos")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call context:getTopColor (number 0 COLOR))) (number 1 COLOR))))
  (targetValue (string [[1,1],[1,1],[1,1],[1,1]]))
)
(example
  (id session:EM0YoSkXrue)
  (context (date 2018 2 19) (graph NaiveKnowledgeGraph ((string [[3],[2],[2],[3],[2]]) (name b) (name c))))
  (timeStamp 2018-03-19T11:36:48.324)
  (NBestInd 9)
  (utterance "acrescentar vermelho em cima laranja")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 3 COLOR)) (number 2 COLOR))))
  (targetValue (string [[3,2],[2],[2],[3,2],[2]]))
)
(example
  (id session:EM0YoSkXrue)
  (context (date 2018 2 19) (graph NaiveKnowledgeGraph ((string [[2],[2],[3],[2],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-03-19T11:37:08.877)
  (NBestInd 14)
  (utterance "acrescentar laranja direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getTopColor (number 2 COLOR))) (number 3 COLOR))))
  (targetValue (string [[2],[2],[3],[2],[2],[2,3]]))
)
(example
  (id session:EM0YoSkXrue)
  (context (date 2018 2 19) (graph NaiveKnowledgeGraph ((string [[0],[0],[3],[0],[3]]) (name b) (name c))))
  (timeStamp 2018-03-19T11:37:21.850)
  (NBestInd 3)
  (utterance "remover azul esquerda")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[0],[3],[0],[3]]))
)
(example
  (id session:EM0YoSkXrue)
  (context (date 2018 2 19) (graph NaiveKnowledgeGraph ((string [[2,2],[2,3],[2,2],[2,3],[2,2]]) (name b) (name c))))
  (timeStamp 2018-03-19T11:37:41.212)
  (NBestInd 3)
  (utterance "acrescentar laranja em cima vermelhos")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 2 COLOR)) (number 3 COLOR))))
  (targetValue (string [[2,2,3],[2,3],[2,2,3],[2,3],[2,2,3]]))
)
(example
  (id session:EM0YoSkXrue)
  (context (date 2018 2 19) (graph NaiveKnowledgeGraph ((string [[3,3],[3,0],[3,3],[3,0]]) (name b) (name c))))
  (timeStamp 2018-03-19T11:38:43.148)
  (NBestInd 17)
  (utterance "trocar azuis por laranjas")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[3,3],[3],[3,3],[3]]))
)
(example
  (id session:EM0YoSkXrue)
  (context (date 2018 2 19) (graph NaiveKnowledgeGraph ((string [[3,3],[3],[3,3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-19T11:38:55.955)
  (NBestInd 17)
  (utterance "acrescentar laranjas todos")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call context:getTopColor (number 1 COLOR))) (number 3 COLOR))))
  (targetValue (string [[3,3,3],[3,3],[3,3,3],[3,3]]))
)
(example
  (id session:EM0YoSkXrue)
  (context (date 2018 2 19) (graph NaiveKnowledgeGraph ((string [[2,2],[3,3],[2,2],[3,3]]) (name b) (name c))))
  (timeStamp 2018-03-19T11:39:23.410)
  (NBestInd 19)
  (utterance "acrescentar laranja em cima laranjas")
  (targetFormula (call wallToString (call context:removeTop (call complement (call context:getTopColor (number 2 COLOR))))))
  (targetValue (string [[2,2],[3],[2,2],[3]]))
)
