(example
  (id session:Fi0GTf7bTfx)
  (context (date 2018 5 19) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-19T08:00:55.582)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:Fi0GTf7bTfx)
  (context (date 2018 5 19) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-19T08:01:00.031)
  (NBestInd 0)
  (utterance apagar)
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 0 COLOR))))))
  (targetValue (string [[],[1],[2],[3]]))
)
(example
  (id session:Fi0GTf7bTfx)
  (context (date 2018 5 19) (graph NaiveKnowledgeGraph ((string [[2],[0],[0],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-06-19T08:01:12.266)
  (NBestInd 30)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
(example
  (id session:Fi0GTf7bTfx)
  (context (date 2018 5 19) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-19T08:01:23.542)
  (NBestInd 0)
  (utterance azul)
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 0 COLOR))))))
  (targetValue (string [[],[1],[2],[3]]))
)
(example
  (id session:Fi0GTf7bTfx)
  (context (date 2018 5 19) (graph NaiveKnowledgeGraph ((string [[1],[0],[3],[3],[2],[0]]) (name b) (name c))))
  (timeStamp 2018-06-19T08:02:15.637)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[1],[],[3],[3],[2],[]]))
)
(example
  (id session:Fi0GTf7bTfx)
  (context (date 2018 5 19) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-19T08:02:20.970)
  (NBestInd 0)
  (utterance castanho)
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 1 COLOR))))
  (targetValue (string [[0],[1,1],[2],[3]]))
)
(example
  (id session:Fi0GTf7bTfx)
  (context (date 2018 5 19) (graph NaiveKnowledgeGraph ((string [[3],[3],[1],[0],[1],[2]]) (name b) (name c))))
  (timeStamp 2018-06-19T08:09:32.033)
  (NBestInd 0)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[3],[3],[],[0],[],[2]]))
)
(example
  (id session:Fi0GTf7bTfx)
  (context (date 2018 5 19) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-19T08:09:37.132)
  (NBestInd 1)
  (utterance azul)
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 0 COLOR))))))
  (targetValue (string [[],[1],[2],[3]]))
)
(example
  (id session:Fi0GTf7bTfx)
  (context (date 2018 5 19) (graph NaiveKnowledgeGraph ((string [[3],[3],[3],[2],[0]]) (name b) (name c))))
  (timeStamp 2018-06-19T08:10:21.608)
  (NBestInd 2)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[],[],[],[2],[0]]))
)
(example
  (id session:Fi0GTf7bTfx)
  (context (date 2018 5 19) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-19T08:10:25.881)
  (NBestInd 6)
  (utterance laranja)
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[0],[1],[2],[]]))
)
(example
  (id session:Fi0GTf7bTfx)
  (context (date 2018 5 19) (graph NaiveKnowledgeGraph ((string [[1],[1],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-06-19T08:10:33.656)
  (NBestInd 0)
  (utterance "adicionar castanho em castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 1 COLOR))))
  (targetValue (string [[1,1],[1,1],[1,1],[1,1]]))
)
(example
  (id session:Fi0GTf7bTfx)
  (context (date 2018 5 19) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-19T08:11:00.190)
  (NBestInd 46)
  (utterance adicionar)
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 2 COLOR)) (number 2 COLOR))))
  (targetValue (string [[0],[1],[2,2],[3]]))
)
(example
  (id session:Fi0GTf7bTfx)
  (context (date 2018 5 19) (graph NaiveKnowledgeGraph ((string [[2],[2],[3],[2],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-06-19T08:11:29.561)
  (NBestInd 17)
  (utterance "adicionar laranja")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getTopColor (number 2 COLOR))) (number 3 COLOR))))
  (targetValue (string [[2],[2],[3],[2],[2],[2,3]]))
)
(example
  (id session:Fi0GTf7bTfx)
  (context (date 2018 5 19) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-19T08:11:35.399)
  (NBestInd 4)
  (utterance em)
  (targetFormula (call wallToString (call context:stackOnTop (call leftMost1 (call context:getTopColor (number 1 COLOR))) (number 1 COLOR))))
  (targetValue (string [[0],[1,1],[2],[3]]))
)
