(example
  (learningMode Implicit)
  (id session:fRfgOYdRnXE)
  (timeStamp 2018-09-14T10:24:57.469)
  (NBestInd 5)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[0],[],[],[0],[3],[]]))
)
(example
  (learningMode Implicit)
  (id session:fRfgOYdRnXE)
  (timeStamp 2018-09-14T10:25:02.175)
  (NBestInd 15)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[],[2],[0],[0],[],[]]))
)
(example
  (learningMode Implicit)
  (id session:fRfgOYdRnXE)
  (timeStamp 2018-09-14T10:25:06.042)
  (NBestInd 0)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[1],[],[1],[0],[0],[1],[0]]))
)
(example
  (learningMode Active)
  (id session:fRfgOYdRnXE)
  (timeStamp 2018-09-14T10:26:01.571)
  (NBestInd 0)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[3],[3],[3],[],[0],[2],[2]]))
)
(example
  (learningMode Implicit)
  (id session:fRfgOYdRnXE)
  (timeStamp 2018-09-14T10:26:12.345)
  (NBestInd 11)
  (utterance "adicionar vermelho esquerda")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 2 COLOR))))
  (targetValue (string [[1],[2],[1],[2],[2],[2,2]]))
)
(example
  (learningMode Implicit)
  (id session:fRfgOYdRnXE)
  (timeStamp 2018-09-14T10:26:17.863)
  (NBestInd 21)
  (utterance "apagar direira")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 0 COLOR))))))
  (targetValue (string [[0],[0],[0],[0],[]]))
)
(example
  (learningMode Implicit)
  (id session:fRfgOYdRnXE)
  (timeStamp 2018-09-14T10:26:44.683)
  (NBestInd 4)
  (utterance "adicionar vermelho vermelho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 2 COLOR)) (number 2 COLOR))))
  (targetValue (string [[1],[1],[1],[1],[2,2],[2,2]]))
)
(example
  (learningMode Implicit)
  (id session:fRfgOYdRnXE)
  (timeStamp 2018-09-14T10:26:50.121)
  (NBestInd 0)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[],[],[],[2],[]]))
)
(example
  (learningMode Active)
  (id session:fRfgOYdRnXE)
  (timeStamp 2018-09-14T10:26:54.101)
  (NBestInd 0)
  (utterance "apagar direira")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getNonEmpty)))))
  (targetValue (string [[3],[2],[2],[1],[0],[3],[]]))
)
(example
  (learningMode Implicit)
  (id session:fRfgOYdRnXE)
  (timeStamp 2018-09-14T10:27:19.818)
  (NBestInd 0)
  (utterance "adicionar vermelho vermelho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 2 COLOR)) (number 2 COLOR))))
  (targetValue (string [[2,2],[2,2],[2,2],[1]]))
)
(example
  (learningMode Implicit)
  (id session:fRfgOYdRnXE)
  (timeStamp 2018-09-14T10:27:26.739)
  (NBestInd 3)
  (utterance "adicionar vermelho azul")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call context:getTopColor (number 2 COLOR))) (number 2 COLOR))))
  (targetValue (string [[0,0,2],[0,2],[0,0,2]]))
)
(example
  (learningMode Implicit)
  (id session:fRfgOYdRnXE)
  (timeStamp 2018-09-14T10:27:38.857)
  (NBestInd 3)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[0,2],[2],[0,2],[2],[0,2]]))
)
(example
  (learningMode Active)
  (id session:fRfgOYdRnXE)
  (timeStamp 2018-09-14T10:27:57.813)
  (NBestInd 78)
  (utterance "adicionar azul")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getNonEmpty) (number 0 COLOR))))
  (targetValue (string [[2,0],[1,0],[1,0],[0,0],[2,0],[3,0],[1,0]]))
)
(example
  (learningMode Implicit)
  (id session:fRfgOYdRnXE)
  (timeStamp 2018-09-14T10:28:03.893)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[1,1],[0],[1,1],[0]]))
)
(example
  (learningMode Implicit)
  (id session:fRfgOYdRnXE)
  (timeStamp 2018-09-14T10:28:19.013)
  (NBestInd 20)
  (utterance "adicionar azul castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 0 COLOR))))
  (targetValue (string [[1,1,0],[0],[1,1,0],[0]]))
)
(example
  (learningMode Implicit)
  (id session:fRfgOYdRnXE)
  (timeStamp 2018-09-14T10:28:29.593)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[0,1],[1],[0,1]]))
)
(example
  (learningMode Implicit)
  (id session:fRfgOYdRnXE)
  (timeStamp 2018-09-14T10:28:34.922)
  (NBestInd 0)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[1],[3,3],[1],[3,3],[1],[3,3]]))
)
(example
  (learningMode Active)
  (id session:fRfgOYdRnXE)
  (timeStamp 2018-09-14T10:28:38.280)
  (NBestInd 2)
  (utterance "adicionar castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call context:getTopColor (number 0 COLOR))) (number 1 COLOR))))
  (targetValue (string [[3,1],[3,1],[2,1],[3,1],[1,1],[3,1]]))
)
