(example
  (learningMode Implicit)
  (id session:g07R51AJ77W)
  (timeStamp 2018-09-14T10:15:03.104)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (learningMode Implicit)
  (id session:g07R51AJ77W)
  (timeStamp 2018-09-14T10:15:08.601)
  (NBestInd 24)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[2],[],[1],[2],[2]]))
)
(example
  (learningMode Implicit)
  (id session:g07R51AJ77W)
  (timeStamp 2018-09-14T10:15:16.384)
  (NBestInd 18)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
(example
  (learningMode Implicit)
  (id session:g07R51AJ77W)
  (timeStamp 2018-09-14T10:15:24.237)
  (NBestInd 2)
  (utterance "adicionar castanho direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getTopColor (number 1 COLOR))) (number 1 COLOR))))
  (targetValue (string [[1],[1],[2],[1,1]]))
)
(example
  (learningMode Implicit)
  (id session:g07R51AJ77W)
  (timeStamp 2018-09-14T10:15:30.220)
  (NBestInd 4)
  (utterance "apagar vermelho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[1],[1],[],[],[],[]]))
)
(example
  (learningMode Implicit)
  (id session:g07R51AJ77W)
  (timeStamp 2018-09-14T10:15:36.341)
  (NBestInd 8)
  (utterance "apagar direita")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 2 COLOR))))))
  (targetValue (string [[0],[0],[0],[2],[]]))
)
(example
  (learningMode Implicit)
  (id session:g07R51AJ77W)
  (timeStamp 2018-09-14T10:15:42.966)
  (NBestInd 0)
  (utterance "adicionar castanho direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 1 COLOR))))
  (targetValue (string [[2],[2],[2],[1],[2,1]]))
)
(example
  (learningMode Implicit)
  (id session:g07R51AJ77W)
  (timeStamp 2018-09-14T10:15:47.689)
  (NBestInd 0)
  (utterance "apagar vermelho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[],[0],[],[0],[0],[0]]))
)
(example
  (learningMode Implicit)
  (id session:g07R51AJ77W)
  (timeStamp 2018-09-14T10:15:51.769)
  (NBestInd 0)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[1,1],[3],[1,1]]))
)
(example
  (learningMode Implicit)
  (id session:g07R51AJ77W)
  (timeStamp 2018-09-14T10:15:55.282)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[0],[1,1],[0]]))
)
(example
  (learningMode Implicit)
  (id session:g07R51AJ77W)
  (timeStamp 2018-09-14T10:15:59.053)
  (NBestInd 0)
  (utterance "apagar vermelho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[0,0],[0],[0,0]]))
)
