(example
  (id session:GrRmLHzyoDd)
  (context (date 2018 5 12) (graph NaiveKnowledgeGraph ((string [[2],[2],[1],[2],[0],[3]]) (name b) (name c))))
  (timeStamp 2018-06-12T11:06:22.068)
  (NBestInd 4)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[2],[2],[1],[2],[],[3]]))
)
(example
  (id session:GrRmLHzyoDd)
  (context (date 2018 5 12) (graph NaiveKnowledgeGraph ((string [[3],[0],[2],[0],[2]]) (name b) (name c))))
  (timeStamp 2018-06-12T11:06:37.211)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[3],[],[2],[],[2]]))
)
(example
  (id session:GrRmLHzyoDd)
  (context (date 2018 5 12) (graph NaiveKnowledgeGraph ((string [[2],[1],[3],[0],[3],[1]]) (name b) (name c))))
  (timeStamp 2018-06-12T11:09:39.590)
  (NBestInd 7)
  (utterance "apagar vermelhp")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[],[1],[3],[0],[3],[1]]))
)
(example
  (id session:GrRmLHzyoDd)
  (context (date 2018 5 12) (graph NaiveKnowledgeGraph ((string [[0],[0],[2],[2],[1]]) (name b) (name c))))
  (timeStamp 2018-06-12T11:12:15.099)
  (NBestInd 1)
  (utterance "apagar vermelho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[0],[0],[],[],[1]]))
)
(example
  (id session:GrRmLHzyoDd)
  (context (date 2018 5 12) (graph NaiveKnowledgeGraph ((string [[0],[2],[0],[3],[3],[1]]) (name b) (name c))))
  (timeStamp 2018-06-12T11:12:52.073)
  (NBestInd 6)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[0],[2],[0],[3],[3],[]]))
)
(example
  (id session:GrRmLHzyoDd)
  (context (date 2018 5 12) (graph NaiveKnowledgeGraph ((string [[1],[1],[2],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-06-12T11:14:16.989)
  (NBestInd 1)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 1 COLOR))))))
  (targetValue (string [[1],[1],[2],[1],[]]))
)
