(example
  (id session:iAiZvcL9YQx)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[3],[2],[0],[2],[0],[0],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T13:53:42.774)
  (NBestInd 6)
  (utterance "apagar vermelho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[3],[],[0],[],[0],[0],[3]]))
)
(example
  (id session:iAiZvcL9YQx)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T13:53:45.927)
  (NBestInd 4)
  (utterance castanho)
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call leftMost1 (call context:getNonEmpty))) (number 1 COLOR))))
  (targetValue (string [[0],[1,1],[2,1],[3,1]]))
)
(example
  (id session:iAiZvcL9YQx)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[2],[3],[0],[2],[1],[2]]) (name b) (name c))))
  (timeStamp 2018-06-15T13:55:08.316)
  (NBestInd 0)
  (utterance "apagar vermelho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[],[3],[0],[],[1],[]]))
)
(example
  (id session:iAiZvcL9YQx)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T13:55:28.131)
  (NBestInd 5)
  (utterance azul)
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getTopColor (number 2 COLOR))) (number 3 COLOR))))
  (targetValue (string [[0],[1],[2,3],[3]]))
)
