(example
  (id session:IRp0ZTRTCwG)
  (context (date 2018 5 12) (graph NaiveKnowledgeGraph ((string [[3],[2],[0],[2],[1],[2],[1]]) (name b) (name c))))
  (timeStamp 2018-06-12T11:16:37.086)
  (NBestInd 4)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[3],[2],[],[2],[1],[2],[1]]))
)
(example
  (id session:IRp0ZTRTCwG)
  (context (date 2018 5 12) (graph NaiveKnowledgeGraph ((string [[2],[1],[2],[3],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-06-12T11:17:09.899)
  (NBestInd 21)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[2],[1],[2],[],[2],[2]]))
)
(example
  (id session:IRp0ZTRTCwG)
  (context (date 2018 5 12) (graph NaiveKnowledgeGraph ((string [[1],[2],[0],[1],[0]]) (name b) (name c))))
  (timeStamp 2018-06-12T11:18:12.243)
  (NBestInd 19)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[],[2],[0],[],[0]]))
)
(example
  (id session:IRp0ZTRTCwG)
  (context (date 2018 5 12) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[1],[1],[2]]) (name b) (name c))))
  (timeStamp 2018-06-12T11:34:44.418)
  (NBestInd 0)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[0],[3],[2],[],[],[2]]))
)
(example
  (id session:IRp0ZTRTCwG)
  (context (date 2018 5 12) (graph NaiveKnowledgeGraph ((string [[2],[1],[3],[3],[3],[0]]) (name b) (name c))))
  (timeStamp 2018-06-12T11:37:03.158)
  (NBestInd 4)
  (utterance "apagar vermelho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[],[1],[3],[3],[3],[0]]))
)
