(example
  (id session:JsmQdS3w4Ky)
  (context (date 2018 5 14) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-14T08:39:25.589)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:JsmQdS3w4Ky)
  (context (date 2018 5 14) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-14T08:40:02.215)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:JsmQdS3w4Ky)
  (context (date 2018 5 14) (graph NaiveKnowledgeGraph ((string [[2],[0],[0],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-06-14T08:41:22.862)
  (NBestInd 34)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
(example
  (id session:JsmQdS3w4Ky)
  (context (date 2018 5 14) (graph NaiveKnowledgeGraph ((string [[3],[0],[1],[2],[2],[0]]) (name b) (name c))))
  (timeStamp 2018-06-14T08:42:49.109)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[3],[],[1],[2],[2],[]]))
)
(example
  (id session:JsmQdS3w4Ky)
  (context (date 2018 5 14) (graph NaiveKnowledgeGraph ((string [[3],[2],[3],[0],[2],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-06-14T08:43:50.072)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[3],[2],[3],[],[2],[2],[2]]))
)
(example
  (id session:JsmQdS3w4Ky)
  (context (date 2018 5 14) (graph NaiveKnowledgeGraph ((string [[0],[1],[0],[0],[1]]) (name b) (name c))))
  (timeStamp 2018-06-14T08:45:25.712)
  (NBestInd 3)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 0 COLOR))))))
  (targetValue (string [[],[1],[0],[0],[1]]))
)
(example
  (id session:JsmQdS3w4Ky)
  (context (date 2018 5 14) (graph NaiveKnowledgeGraph ((string [[3],[3],[3],[2]]) (name b) (name c))))
  (timeStamp 2018-06-14T08:46:08.789)
  (NBestInd 1)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[3],[2]]))
)
