(example
  (id session:kIH1reNYHZq)
  (context (date 2018 5 14) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-14T12:17:19.610)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:kIH1reNYHZq)
  (context (date 2018 5 14) (graph NaiveKnowledgeGraph ((string [[3],[0],[1],[2],[2],[0]]) (name b) (name c))))
  (timeStamp 2018-06-14T12:23:00.496)
  (NBestInd 7)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[3],[],[1],[2],[2],[]]))
)
(example
  (id session:kIH1reNYHZq)
  (context (date 2018 5 14) (graph NaiveKnowledgeGraph ((string [[3],[2],[3],[0],[2],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-06-14T12:24:23.324)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 0 COLOR))))))
  (targetValue (string [[3],[2],[3],[],[2],[2],[2]]))
)
(example
  (id session:kIH1reNYHZq)
  (context (date 2018 5 14) (graph NaiveKnowledgeGraph ((string [[0],[1],[3],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-14T12:28:15.387)
  (NBestInd 10)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[0],[],[3],[],[2],[3]]))
)
