(example
  (learningMode Implicit)
  (id session:L0hFqtTn64i)
  (timeStamp 2018-09-13T12:05:06.973)
  (NBestInd 2)
  (utterance "wjner wer")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (learningMode Implicit)
  (id session:L0hFqtTn64i)
  (timeStamp 2018-09-13T12:05:19.078)
  (NBestInd 79)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[2],[],[1],[2],[2]]))
)
(example
  (learningMode Implicit)
  (id session:L0hFqtTn64i)
  (timeStamp 2018-09-13T12:05:26.070)
  (NBestInd 23)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
(example
  (learningMode Implicit)
  (id session:L0hFqtTn64i)
  (timeStamp 2018-09-13T12:05:32.107)
  (NBestInd 3)
  (utterance "adiconar castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getTopColor (number 1 COLOR))) (number 1 COLOR))))
  (targetValue (string [[1],[1],[2],[1,1]]))
)
(example
  (learningMode Implicit)
  (id session:L0hFqtTn64i)
  (timeStamp 2018-09-13T12:07:43.841)
  (NBestInd 38)
  (utterance "adicionar azul")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 0 COLOR)) (number 0 COLOR))))
  (targetValue (string [[2],[2],[0,0],[2],[0,0]]))
)
(example
  (learningMode Implicit)
  (id session:L0hFqtTn64i)
  (timeStamp 2018-09-13T12:07:53.764)
  (NBestInd 44)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[1],[],[],[1],[1],[1]]))
)
(example
  (learningMode Implicit)
  (id session:L0hFqtTn64i)
  (timeStamp 2018-09-13T12:08:02.850)
  (NBestInd 6)
  (utterance "adiconar castanho laranja")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 3 COLOR)) (number 1 COLOR))))
  (targetValue (string [[1],[3,1],[3,1],[1]]))
)
(example
  (learningMode Implicit)
  (id session:L0hFqtTn64i)
  (timeStamp 2018-09-13T12:08:06.849)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[1],[1],[],[1],[],[]]))
)
(example
  (learningMode Implicit)
  (id session:L0hFqtTn64i)
  (timeStamp 2018-09-13T12:08:17.075)
  (NBestInd 21)
  (utterance "adicionar laranja")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call context:getTopColor (number 3 COLOR))) (number 3 COLOR))))
  (targetValue (string [[3],[0,3],[0,3],[0,3],[0,3]]))
)
(example
  (learningMode Implicit)
  (id session:L0hFqtTn64i)
  (timeStamp 2018-09-13T12:08:23.462)
  (NBestInd 1)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[1],[1,3],[1],[1,3],[1]]))
)
