(example
  (id session:LMiRZUMfx7w)
  (context (date 2018 5 16) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-16T13:54:09.015)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:LMiRZUMfx7w)
  (context (date 2018 5 16) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-16T13:54:13.541)
  (NBestInd 4)
  (utterance apagar)
  (targetFormula (call wallToString (call context:removeTop (call complement (call leftMost1 (call context:getTopColor (number 0 COLOR)))))))
  (targetValue (string [[0],[],[],[]]))
)
(example
  (id session:LMiRZUMfx7w)
  (context (date 2018 5 16) (graph NaiveKnowledgeGraph ((string [[2],[0],[0],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-06-16T13:54:26.764)
  (NBestInd 46)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
