(example
  (id session:LOK8ypVKmE9)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[1],[3],[2],[3],[0],[2]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:28:34.805)
  (NBestInd 2)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[0],[2]]))
)
(example
  (id session:LOK8ypVKmE9)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:28:42.709)
  (NBestInd 12)
  (utterance azul)
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 2 COLOR)) (number 3 COLOR))))
  (targetValue (string [[0],[1],[2,3],[3]]))
)
(example
  (id session:LOK8ypVKmE9)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:28:52.891)
  (NBestInd 104)
  (utterance azul)
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 1 COLOR))))))
  (targetValue (string [[0],[],[2],[3]]))
)
(example
  (id session:LOK8ypVKmE9)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[0],[0],[2],[1]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:33:49.605)
  (NBestInd 24)
  (utterance "apagar vermelho")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 2 COLOR))))))
  (targetValue (string [[0],[0],[0],[],[1]]))
)
(example
  (id session:LOK8ypVKmE9)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:33:56.194)
  (NBestInd 4)
  (utterance azul)
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getTopColor (number 1 COLOR))) (number 3 COLOR))))
  (targetValue (string [[0],[1,3],[2],[3]]))
)
(example
  (id session:LOK8ypVKmE9)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[2],[2],[2],[0],[3],[2]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:35:17.563)
  (NBestInd 13)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[2],[2],[2],[0],[],[2]]))
)
(example
  (id session:LOK8ypVKmE9)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:35:22.071)
  (NBestInd 2)
  (utterance castanho)
  (targetFormula (call wallToString (call context:stackOnTop (call leftMost1 (call context:getTopColor (number 1 COLOR))) (number 1 COLOR))))
  (targetValue (string [[0],[1,1],[2],[3]]))
)
(example
  (id session:LOK8ypVKmE9)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[3],[3],[1],[1],[0]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:42:54.076)
  (NBestInd 1)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[0],[1],[],[],[1],[1],[0]]))
)
(example
  (id session:LOK8ypVKmE9)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:43:04.312)
  (NBestInd 57)
  (utterance vermelho)
  (targetFormula (call wallToString (call context:removeTop (call context:getNonEmpty))))
  (targetValue (string [[],[],[],[]]))
)
(example
  (id session:LOK8ypVKmE9)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:43:08.306)
  (NBestInd 57)
  (utterance vermelho)
  (targetFormula (call wallToString (call context:stackOnTop (call leftMost1 (call context:getNonEmpty)) (number 0 COLOR))))
  (targetValue (string [[0,0],[1],[2],[3]]))
)
(example
  (id session:LOK8ypVKmE9)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:43:14.256)
  (NBestInd 57)
  (utterance vermelho)
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 2 COLOR)) (number 3 COLOR))))
  (targetValue (string [[0],[1],[2,3],[3]]))
)
(example
  (id session:LOK8ypVKmE9)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[1],[1],[1],[1],[3],[2],[0]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:45:12.201)
  (NBestInd 0)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[1],[1],[1],[1],[],[2],[0]]))
)
(example
  (id session:LOK8ypVKmE9)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:45:16.724)
  (NBestInd 0)
  (utterance vermelho)
  (targetFormula (call wallToString (call context:removeTop (call context:getNonEmpty))))
  (targetValue (string [[],[],[],[]]))
)
