(example
  (id session:mlTr7UzhKkV)
  (context (date 2018 5 14) (graph NaiveKnowledgeGraph ((string [[3],[3],[1],[0],[1],[2]]) (name b) (name c))))
  (timeStamp 2018-06-14T08:27:39.846)
  (NBestInd 5)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[3],[3],[],[0],[],[2]]))
)
(example
  (id session:mlTr7UzhKkV)
  (context (date 2018 5 14) (graph NaiveKnowledgeGraph ((string [[3],[3],[3],[2],[0]]) (name b) (name c))))
  (timeStamp 2018-06-14T08:28:02.196)
  (NBestInd 15)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[],[],[],[2],[0]]))
)
(example
  (id session:mlTr7UzhKkV)
  (context (date 2018 5 14) (graph NaiveKnowledgeGraph ((string [[2],[2],[3],[3],[3],[3],[1]]) (name b) (name c))))
  (timeStamp 2018-06-14T08:28:28.826)
  (NBestInd 0)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[2],[3],[3],[3],[3],[]]))
)
(example
  (id session:mlTr7UzhKkV)
  (context (date 2018 5 14) (graph NaiveKnowledgeGraph ((string [[1],[3],[2],[3],[0],[2]]) (name b) (name c))))
  (timeStamp 2018-06-14T08:30:04.362)
  (NBestInd 0)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[],[3],[2],[3],[0],[2]]))
)
(example
  (id session:mlTr7UzhKkV)
  (context (date 2018 5 14) (graph NaiveKnowledgeGraph ((string [[3],[3],[2],[2],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-06-14T08:31:51.780)
  (NBestInd 0)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[],[],[2],[2],[1],[1]]))
)
