(example
  (learningMode Implicit)
  (id session:MTW0drRHvxk)
  (timeStamp 2018-10-12T16:35:21.680)
  (NBestInd 4)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[1],[3],[2],[3],[],[1],[3]]))
)
(example
  (learningMode Implicit)
  (id session:MTW0drRHvxk)
  (timeStamp 2018-10-12T16:48:55.526)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (learningMode Implicit)
  (id session:MTW0drRHvxk)
  (timeStamp 2018-10-12T16:53:33.958)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
