(example
  (id session:nJh2wEWQxRm)
  (context (date 2018 5 27) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-27T12:17:33.228)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:nJh2wEWQxRm)
  (context (date 2018 5 27) (graph NaiveKnowledgeGraph ((string [[2],[3],[1],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-06-27T12:17:49.437)
  (NBestInd 79)
  (utterance "apgar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[2],[],[1],[2],[2]]))
)
(example
  (id session:nJh2wEWQxRm)
  (context (date 2018 5 27) (graph NaiveKnowledgeGraph ((string [[2],[0],[0],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-06-27T12:18:02.988)
  (NBestInd 32)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
(example
  (id session:nJh2wEWQxRm)
  (context (date 2018 5 27) (graph NaiveKnowledgeGraph ((string [[3],[0],[1],[2],[2],[0]]) (name b) (name c))))
  (timeStamp 2018-06-27T12:50:00.598)
  (NBestInd 22)
  (utterance azul)
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 2 COLOR))))))
  (targetValue (string [[3],[0],[1],[],[2],[0]]))
)
(example
  (id session:nJh2wEWQxRm)
  (context (date 2018 5 27) (graph NaiveKnowledgeGraph ((string [[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-27T12:56:46.737)
  (NBestInd 1)
  (utterance clv)
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call context:getTopColor (number 1 COLOR))) (number 3 COLOR))))
  (targetValue (string [[3,3],[3,3],[3,3],[3,3]]))
)
