(example
  (id session:o7wXCqqUVth)
  (context (date 2018 5 16) (graph NaiveKnowledgeGraph ((string [[2],[3],[1],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-06-16T14:00:41.682)
  (NBestInd 7)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[2],[],[1],[2],[2]]))
)
(example
  (id session:o7wXCqqUVth)
  (context (date 2018 5 16) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-16T14:00:45.688)
  (NBestInd 3)
  (utterance apagar)
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[0],[1],[2],[]]))
)
(example
  (id session:o7wXCqqUVth)
  (context (date 2018 5 16) (graph NaiveKnowledgeGraph ((string [[1],[3],[1],[0],[0],[1],[0]]) (name b) (name c))))
  (timeStamp 2018-06-16T14:01:00.485)
  (NBestInd 0)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[1],[],[1],[0],[0],[1],[0]]))
)
(example
  (id session:o7wXCqqUVth)
  (context (date 2018 5 18) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-18T08:07:18.547)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:o7wXCqqUVth)
  (context (date 2018 5 18) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-18T08:07:29.340)
  (NBestInd 23)
  (utterance apagar)
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 2 COLOR))))))
  (targetValue (string [[0],[1],[],[3]]))
)
(example
  (id session:o7wXCqqUVth)
  (context (date 2018 5 18) (graph NaiveKnowledgeGraph ((string [[2],[0],[0],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-06-18T08:07:52.788)
  (NBestInd 18)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
(example
  (id session:o7wXCqqUVth)
  (context (date 2018 5 18) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-18T08:07:57.449)
  (NBestInd 0)
  (utterance azul)
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[1],[2],[3]]))
)
(example
  (id session:o7wXCqqUVth)
  (context (date 2018 5 18) (graph NaiveKnowledgeGraph ((string [[1],[0],[3],[3],[2],[0]]) (name b) (name c))))
  (timeStamp 2018-06-18T08:08:03.298)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[1],[],[3],[3],[2],[]]))
)
(example
  (id session:o7wXCqqUVth)
  (context (date 2018 5 18) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-18T08:08:10.569)
  (NBestInd 6)
  (utterance castanho)
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 1 COLOR))))))
  (targetValue (string [[0],[],[2],[3]]))
)
(example
  (id session:o7wXCqqUVth)
  (context (date 2018 5 18) (graph NaiveKnowledgeGraph ((string [[0],[3],[3],[0],[0]]) (name b) (name c))))
  (timeStamp 2018-06-18T08:08:20.196)
  (NBestInd 9)
  (utterance "adicionar laranja")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 3 COLOR))))
  (targetValue (string [[0],[3],[3],[0],[0,3]]))
)
(example
  (id session:o7wXCqqUVth)
  (context (date 2018 5 18) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-18T08:08:41.962)
  (NBestInd 2)
  (utterance adicionar)
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 0 COLOR))))
  (targetValue (string [[0],[1],[2],[3,0]]))
)
(example
  (id session:o7wXCqqUVth)
  (context (date 2018 5 18) (graph NaiveKnowledgeGraph ((string [[2],[0],[3],[1]]) (name b) (name c))))
  (timeStamp 2018-06-18T08:09:03.526)
  (NBestInd 0)
  (utterance laranja)
)
(example
  (id session:o7wXCqqUVth)
  (context (date 2018 5 18) (graph NaiveKnowledgeGraph ((string [[3],[3],[3],[2]]) (name b) (name c))))
  (timeStamp 2018-06-18T08:09:21.996)
  (NBestInd 1)
  (utterance "adicionar laranja")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 3 COLOR))))
  (targetValue (string [[3],[3],[3],[2,3]]))
)
(example
  (id session:o7wXCqqUVth)
  (context (date 2018 5 18) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-18T08:09:27.340)
  (NBestInd 2)
  (utterance laranja)
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getNonEmpty)))))
  (targetValue (string [[0],[1],[2],[]]))
)
