(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:30:19.642)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[2],[3],[1],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:30:27.468)
  (NBestInd 24)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[2],[],[1],[2],[2]]))
)
(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[2],[0],[0],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:30:36.344)
  (NBestInd 18)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[1],[0],[3],[3],[2],[0]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:30:42.081)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[1],[],[3],[3],[2],[]]))
)
(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[3],[0],[1],[0],[3],[1]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:30:47.296)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[3],[],[1],[],[3],[1]]))
)
(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[2],[3],[2],[2],[2],[1],[3]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:30:53.688)
  (NBestInd 0)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[3],[2],[2],[2],[],[3]]))
)
(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[2],[0],[1],[1],[2],[3],[0]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:30:59.380)
  (NBestInd 0)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[2],[0],[1],[1],[2],[],[0]]))
)
(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[0],[2],[0],[2]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:31:09.804)
  (NBestInd 23)
  (utterance "apagar direita")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 2 COLOR))))))
  (targetValue (string [[0],[2],[0],[]]))
)
(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[1],[1],[2],[1],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:31:30.938)
  (NBestInd 13)
  (utterance "adicionar vermelho esquerda")
  (targetFormula (call wallToString (call context:stackOnTop (call leftMost1 (call context:getTopColor (number 1 COLOR))) (number 2 COLOR))))
  (targetValue (string [[1,2],[1],[2],[1],[2],[2]]))
)
(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[3],[0],[0],[0]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:31:54.076)
  (NBestInd 2)
  (utterance "adicionar azul esquerda")
  (targetFormula (call wallToString (call context:stackOnTop (call leftMost1 (call context:getNonEmpty)) (number 0 COLOR))))
  (targetValue (string [[3,0],[0],[0],[0]]))
)
(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[2],[0],[0],[0],[0],[0]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:32:01.553)
  (NBestInd 0)
  (utterance "apagar esquerda")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[0],[0],[0],[0],[0]]))
)
(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[2],[1],[2],[2],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:32:08.412)
  (NBestInd 0)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[],[2],[2],[2],[2]]))
)
(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[2],[0],[1],[0],[1],[2],[1]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:32:13.448)
  (NBestInd 1)
  (utterance "apagar direita")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getNonEmpty)))))
  (targetValue (string [[2],[0],[1],[0],[1],[2],[]]))
)
(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[1],[1],[1],[1],[2]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:32:22.107)
  (NBestInd 0)
  (utterance "apagar direita")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getNonEmpty)))))
  (targetValue (string [[1],[1],[1],[1],[]]))
)
(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[1],[0],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:32:31.944)
  (NBestInd 2)
  (utterance "adicionar castanho direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 1 COLOR))))
  (targetValue (string [[1],[0],[1],[1,1]]))
)
(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[3],[3],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:34:39.768)
  (NBestInd 0)
  (utterance "apagar direita")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getNonEmpty)))))
  (targetValue (string [[3],[3],[2],[]]))
)
(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[1],[2],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:34:51.918)
  (NBestInd 0)
  (utterance "adicionar vermelho direita")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 2 COLOR))))
  (targetValue (string [[1],[2],[2],[2,2]]))
)
(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[0],[1],[0],[1]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:35:11.049)
  (NBestInd 0)
  (utterance "adicionar azul em azul")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 0 COLOR)) (number 0 COLOR))))
  (targetValue (string [[0,0],[1],[0,0],[1]]))
)
(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[2,2],[0,0],[2,2],[0,0],[2,2]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:35:31.162)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[2,2],[0],[2,2],[0],[2,2]]))
)
(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[2,2],[0],[2,2],[0],[2,2]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:35:56.144)
  (NBestInd 14)
  (utterance "adicionar laranja em vermelho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 2 COLOR)) (number 3 COLOR))))
  (targetValue (string [[2,2,3],[0],[2,2,3],[0],[2,2,3]]))
)
(example
  (id session:oNch2vEBXjd)
  (context (date 2018 6 2) (graph NaiveKnowledgeGraph ((string [[1,1],[1,3],[1,1],[1,3],[1,1]]) (name b) (name c))))
  (timeStamp 2018-07-02T13:36:13.255)
  (NBestInd 2)
  (utterance "adicionar laranja em castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 3 COLOR))))
  (targetValue (string [[1,1,3],[1,3],[1,1,3],[1,3],[1,1,3]]))
)
