(example
  (id session:PN8ZfQOpaXn)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[2],[2],[3],[3],[3],[3],[1]]) (name b) (name c))))
  (timeStamp 2018-06-15T23:16:57.346)
  (NBestInd 3)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getNonEmpty)))))
  (targetValue (string [[2],[2],[3],[3],[3],[3],[]]))
)
(example
  (id session:PN8ZfQOpaXn)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[1],[3],[2],[3],[0],[2]]) (name b) (name c))))
  (timeStamp 2018-06-15T23:17:25.378)
  (NBestInd 0)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 1 COLOR))))))
  (targetValue (string [[],[3],[2],[3],[0],[2]]))
)
(example
  (id session:PN8ZfQOpaXn)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T23:22:33.002)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
