(example
  (id session:qVpdosfrbHz)
  (context (date 2018 5 14) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[0],[0],[3],[2]]) (name b) (name c))))
  (timeStamp 2018-06-14T23:30:50.716)
  (NBestInd 5)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[0],[],[2],[0],[0],[3],[2]]))
)
(example
  (id session:qVpdosfrbHz)
  (context (date 2018 5 14) (graph NaiveKnowledgeGraph ((string [[0],[2],[3],[1],[3],[0]]) (name b) (name c))))
  (timeStamp 2018-06-14T23:31:54.712)
  (NBestInd 27)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[0],[2],[],[1],[],[0]]))
)
(example
  (id session:qVpdosfrbHz)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:06:25.732)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
