(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 13) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-13T10:45:47.828)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 13) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-13T10:46:07.345)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 0 COLOR))))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 13) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-13T10:46:58.341)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 13) (graph NaiveKnowledgeGraph ((string [[2],[3],[1],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-03-13T10:51:00.246)
  (NBestInd 24)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[2],[],[1],[2],[2]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 13) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-13T10:52:29.132)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 13) (graph NaiveKnowledgeGraph ((string [[2],[3],[1],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-03-13T10:52:38.058)
  (NBestInd 24)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[2],[],[1],[2],[2]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 13) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-13T11:03:35.205)
  (NBestInd 2)
  (utterance "apgar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 13) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-13T11:06:35.829)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 13) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-13T11:08:25.437)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 13) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-13T11:09:12.185)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 13) (graph NaiveKnowledgeGraph ((string [[3],[2],[2],[2],[3],[2]]) (name b) (name c))))
  (timeStamp 2018-03-13T11:09:41.839)
  (NBestInd 35)
  (utterance "apagar vermelhos")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[3],[],[],[],[3],[]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 13) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-13T13:36:08.276)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 13) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-13T13:42:31.310)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 13) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-13T13:49:32.751)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 13) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-13T13:52:11.883)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 13) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-13T13:57:33.560)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 13) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-13T14:00:09.171)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 13) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-13T14:34:41.243)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 16) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-16T14:20:30.522)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 16) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-16T14:23:51.004)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 16) (graph NaiveKnowledgeGraph ((string [[3],[2],[2],[2],[3],[2]]) (name b) (name c))))
  (timeStamp 2018-03-16T14:24:05.985)
  (NBestInd 35)
  (utterance "apagar vermelhos")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[3],[],[],[],[3],[]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 16) (graph NaiveKnowledgeGraph ((string [[3],[2],[3],[2],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-03-16T14:24:17.023)
  (NBestInd 1)
  (utterance "acrescentar vermelhos")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 2 COLOR)) (number 2 COLOR))))
  (targetValue (string [[3],[2,2],[3],[2,2],[3],[3]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 16) (graph NaiveKnowledgeGraph ((string [[0],[0],[0],[0]]) (name b) (name c))))
  (timeStamp 2018-03-16T14:24:24.582)
  (NBestInd 8)
  (utterance "acrescentar azul")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getTopColor (number 0 COLOR))) (number 0 COLOR))))
  (targetValue (string [[0],[0],[0],[0,0]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 16) (graph NaiveKnowledgeGraph ((string [[3],[0],[3],[3],[0]]) (name b) (name c))))
  (timeStamp 2018-03-16T14:24:43.904)
  (NBestInd 0)
  (utterance "apagar azuis")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[3],[],[3],[3],[]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 16) (graph NaiveKnowledgeGraph ((string [[1],[2],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-03-16T14:24:57.771)
  (NBestInd 20)
  (utterance "acrescentar castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getTopColor (number 2 COLOR))) (number 1 COLOR))))
  (targetValue (string [[1],[2],[2],[2,1]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 16) (graph NaiveKnowledgeGraph ((string [[2],[2],[3],[3],[2]]) (name b) (name c))))
  (timeStamp 2018-03-16T14:25:09.786)
  (NBestInd 17)
  (utterance "apagar vermelho")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 2 COLOR))))))
  (targetValue (string [[2],[2],[3],[3],[]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 16) (graph NaiveKnowledgeGraph ((string [[0],[3],[3],[0],[0]]) (name b) (name c))))
  (timeStamp 2018-03-16T14:25:19.721)
  (NBestInd 5)
  (utterance "acrescentar laranja")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 3 COLOR))))
  (targetValue (string [[0],[3],[3],[0],[0,3]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 16) (graph NaiveKnowledgeGraph ((string [[2],[2],[0],[0],[0]]) (name b) (name c))))
  (timeStamp 2018-03-16T14:25:27.765)
  (NBestInd 0)
  (utterance "acrescentar vermelho")
  (targetFormula (call wallToString (call context:stackOnTop (call rightMost1 (call context:getNonEmpty)) (number 2 COLOR))))
  (targetValue (string [[2],[2],[0],[0],[0,2]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 2 16) (graph NaiveKnowledgeGraph ((string [[1],[3],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-03-16T14:25:45.759)
  (NBestInd 102)
  (utterance "acrescentar castanhos")
  (targetFormula (call wallToString (call context:removeTop (call complement (call rightMost1 (call context:getTopColor (number 3 COLOR)))))))
  (targetValue (string [[],[3],[],[]]))
)
(example
  (id session:rbZpe3Yvcub)
  (context (date 2018 3 26) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-04-26T14:42:56.106)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
