(example
  (id session:SFeW7Ahxvg9)
  (context (date 2018 5 16) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-16T11:40:24.078)
  (NBestInd 2)
  (utterance "asa ss")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:SFeW7Ahxvg9)
  (context (date 2018 5 16) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-16T11:40:26.895)
  (NBestInd 4)
  (utterance ss)
  (targetFormula (call wallToString (call context:removeTop (call complement (call leftMost1 (call context:getTopColor (number 0 COLOR)))))))
  (targetValue (string [[0],[],[],[]]))
)
