(example
  (id session:sySSWn2wkWy)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[1],[0],[3],[3],[2],[0]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:07:15.747)
  (NBestInd 4)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[1],[],[3],[3],[2],[]]))
)
(example
  (id session:sySSWn2wkWy)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:08:54.840)
  (NBestInd 0)
  (utterance apagar)
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 0 COLOR)) (number 0 COLOR))))
  (targetValue (string [[0,0],[1],[2],[3]]))
)
(example
  (id session:sySSWn2wkWy)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:09:40.964)
  (NBestInd 0)
  (utterance apagar)
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 0 COLOR)) (number 0 COLOR))))
  (targetValue (string [[0,0],[1],[2],[3]]))
)
(example
  (id session:sySSWn2wkWy)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:09:55.587)
  (NBestInd 8)
  (utterance apagar)
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 0 COLOR)) (number 2 COLOR))))
  (targetValue (string [[0,2],[1],[2],[3]]))
)
(example
  (id session:sySSWn2wkWy)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[3],[2],[3],[0],[2],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:13:40.744)
  (NBestInd 1)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[3],[2],[3],[],[2],[2],[2]]))
)
(example
  (id session:sySSWn2wkWy)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:17:31.231)
  (NBestInd 33)
  (utterance azul)
  (targetFormula (call wallToString (call context:removeTop (call context:getNonEmpty))))
  (targetValue (string [[],[],[],[]]))
)
