(example
  (id session:to4vlECe8w1)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[2],[2],[0],[3],[1],[1],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:49:40.863)
  (NBestInd 4)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[2],[2],[],[3],[1],[1],[3]]))
)
(example
  (id session:to4vlECe8w1)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:49:49.379)
  (NBestInd 22)
  (utterance castanho)
  (targetFormula (call wallToString (call context:stackOnTop (call leftMost1 (call context:getNonEmpty)) (number 3 COLOR))))
  (targetValue (string [[0,3],[1],[2],[3]]))
)
(example
  (id session:to4vlECe8w1)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[3],[3],[2],[3],[1],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:52:01.427)
  (NBestInd 27)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[0],[],[],[2],[],[1],[]]))
)
(example
  (id session:to4vlECe8w1)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:52:06.782)
  (NBestInd 8)
  (utterance vermelho)
  (targetFormula (call wallToString (call context:removeTop (call complement (call context:getTopColor (number 2 COLOR))))))
  (targetValue (string [[],[],[2],[]]))
)
(example
  (id session:to4vlECe8w1)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[1],[2],[2],[0],[1],[0]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:53:08.166)
  (NBestInd 0)
  (utterance "apagar vermelho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[1],[],[],[0],[1],[0]]))
)
(example
  (id session:to4vlECe8w1)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:53:11.541)
  (NBestInd 5)
  (utterance castanho)
  (targetFormula (call wallToString (call context:stackOnTop (call leftMost1 (call context:getTopColor (number 0 COLOR))) (number 0 COLOR))))
  (targetValue (string [[0,0],[1],[2],[3]]))
)
(example
  (id session:to4vlECe8w1)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[3],[1],[2],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:54:22.706)
  (NBestInd 31)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[0],[],[3],[],[2],[2],[3]]))
)
(example
  (id session:to4vlECe8w1)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:54:26.402)
  (NBestInd 2)
  (utterance laranja)
  (targetFormula (call wallToString (call context:removeTop (call complement (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[],[],[],[3]]))
)
(example
  (id session:to4vlECe8w1)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[2],[0],[3],[1],[2],[3],[2]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:54:56.998)
  (NBestInd 0)
  (utterance "apagar vermelho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[],[0],[3],[1],[],[3],[]]))
)
(example
  (id session:to4vlECe8w1)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T08:55:00.275)
  (NBestInd 5)
  (utterance castanho)
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 0 COLOR)) (number 1 COLOR))))
  (targetValue (string [[0,1],[1],[2],[3]]))
)
