(example
  (id session:tpNPOYVOYxw)
  (context (date 2018 5 22) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-22T15:27:00.346)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:tpNPOYVOYxw)
  (context (date 2018 5 22) (graph NaiveKnowledgeGraph ((string [[0],[2],[0],[1],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-22T15:28:05.526)
  (NBestInd 13)
  (utterance apagar)
  (targetFormula (call wallToString (call context:removeTop (call context:getNonEmpty))))
  (targetValue (string [[],[],[],[],[],[]]))
)
