(example
  (id session:UO6BIbUkc6O)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[3],[1],[3],[2],[0]]) (name b) (name c))))
  (timeStamp 2018-06-15T13:45:59.116)
  (NBestInd 7)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[0],[],[1],[],[2],[0]]))
)
(example
  (id session:UO6BIbUkc6O)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T13:46:02.202)
  (NBestInd 3)
  (utterance castanho)
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call leftMost1 (call context:getNonEmpty))) (number 0 COLOR))))
  (targetValue (string [[0],[1,0],[2,0],[3,0]]))
)
(example
  (id session:UO6BIbUkc6O)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[3],[0],[1],[3],[1]]) (name b) (name c))))
  (timeStamp 2018-06-15T13:47:11.997)
  (NBestInd 15)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[3],[],[1],[3],[1]]))
)
(example
  (id session:UO6BIbUkc6O)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T13:47:21.556)
  (NBestInd 5)
  (utterance vermelho)
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 2 COLOR)) (number 1 COLOR))))
  (targetValue (string [[0],[1],[2,1],[3]]))
)
(example
  (id session:UO6BIbUkc6O)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[2],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T13:51:34.534)
  (NBestInd 38)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[0],[],[2],[2],[3],[3]]))
)
(example
  (id session:UO6BIbUkc6O)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T13:51:44.563)
  (NBestInd 25)
  (utterance castanho)
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 1 COLOR))))))
  (targetValue (string [[0],[],[2],[3]]))
)
(example
  (id session:UO6BIbUkc6O)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T13:51:58.997)
  (NBestInd 7)
  (utterance azul)
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call context:getTopColor (number 0 COLOR))) (number 0 COLOR))))
  (targetValue (string [[0],[1,0],[2,0],[3,0]]))
)
(example
  (id session:UO6BIbUkc6O)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[3],[1],[0],[1],[0],[0]]) (name b) (name c))))
  (timeStamp 2018-06-15T13:52:10.641)
  (NBestInd 0)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[3],[],[0],[],[0],[0]]))
)
(example
  (id session:UO6BIbUkc6O)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T13:52:15.661)
  (NBestInd 14)
  (utterance vermelho)
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[0],[1],[],[3]]))
)
(example
  (id session:UO6BIbUkc6O)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[3],[0],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T13:52:25.256)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[],[3],[],[3],[3]]))
)
(example
  (id session:UO6BIbUkc6O)
  (context (date 2018 5 15) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3]]) (name b) (name c))))
  (timeStamp 2018-06-15T13:52:47.339)
  (NBestInd 1)
  (utterance laranja)
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[0],[1],[2],[]]))
)
