(example (learningMode Explicit) (id session:V00uVpEjVor) (timeStamp 2018-09-13T15:59:48.878) (NBestInd 0) (utterance azul))
(example (learningMode Explicit) (id session:V00uVpEjVor) (timeStamp 2018-09-13T16:00:02.316) (NBestInd 0) (utterance direita))
(example (learningMode Explicit) (id session:V00uVpEjVor) (timeStamp 2018-09-13T16:00:15.346) (NBestInd 0) (utterance vermelho))
(example
  (learningMode Implicit)
  (id session:V00uVpEjVor)
  (timeStamp 2018-09-13T16:00:25.503)
  (NBestInd 5)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[3],[2],[2],[2],[],[3]]))
)
(example
  (learningMode Implicit)
  (id session:V00uVpEjVor)
  (timeStamp 2018-09-13T16:00:31.367)
  (NBestInd 3)
  (utterance "apagar vermelho")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 2 COLOR))))))
  (targetValue (string [[1],[],[0],[0],[0]]))
)
(example
  (learningMode Implicit)
  (id session:V00uVpEjVor)
  (timeStamp 2018-09-13T16:00:36.604)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 0 COLOR))))))
  (targetValue (string [[3],[2],[2],[1],[],[3],[1]]))
)
(example
  (learningMode Active)
  (id session:V00uVpEjVor)
  (timeStamp 2018-09-13T16:00:48.019)
  (NBestInd 17)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[0],[],[1],[0],[],[1],[0]]))
)
(example
  (learningMode Implicit)
  (id session:V00uVpEjVor)
  (timeStamp 2018-09-13T16:00:52.739)
  (NBestInd 0)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[0],[0],[0],[],[0]]))
)
(example
  (learningMode Implicit)
  (id session:V00uVpEjVor)
  (timeStamp 2018-09-13T16:01:08.265)
  (NBestInd 23)
  (utterance "adicionar castanho esquerda")
  (targetFormula (call wallToString (call context:stackOnTop (call leftMost1 (call context:getTopColor (number 2 COLOR))) (number 1 COLOR))))
  (targetValue (string [[2,1],[1],[1],[2]]))
)
(example
  (learningMode Implicit)
  (id session:V00uVpEjVor)
  (timeStamp 2018-09-13T16:01:18.787)
  (NBestInd 3)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[3],[2],[2],[2],[2],[]]))
)
(example
  (learningMode Implicit)
  (id session:V00uVpEjVor)
  (timeStamp 2018-09-13T16:01:24.286)
  (NBestInd 3)
  (utterance "apagar esquerda")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[2],[1],[1]]))
)
(example
  (learningMode Active)
  (id session:V00uVpEjVor)
  (timeStamp 2018-09-13T16:01:30.632)
  (NBestInd 6)
  (utterance "adicionar castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getNonEmpty) (number 1 COLOR))))
  (targetValue (string [[1,1],[2,1],[2,1],[0,1],[3,1],[1,1]]))
)
(example
  (learningMode Implicit)
  (id session:V00uVpEjVor)
  (timeStamp 2018-09-13T16:01:53.475)
  (NBestInd 11)
  (utterance "adicionar vermelho")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call rightMost1 (call context:getNonEmpty))) (number 2 COLOR))))
  (targetValue (string [[0,2],[0,2],[0,2],[0]]))
)
(example
  (learningMode Implicit)
  (id session:V00uVpEjVor)
  (timeStamp 2018-09-13T16:02:01.442)
  (NBestInd 5)
  (utterance "adicionar castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call complement (call rightMost1 (call context:getNonEmpty))) (number 1 COLOR))))
  (targetValue (string [[0,2,1],[0,2,1],[0,2,1],[0]]))
)
(example
  (learningMode Implicit)
  (id session:V00uVpEjVor)
  (timeStamp 2018-09-13T16:02:07.823)
  (NBestInd 0)
  (utterance "apagar castanho direita")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 1 COLOR))))))
  (targetValue (string [[0,2,1],[0,2,1],[0,2],[0]]))
)
(example
  (learningMode Implicit)
  (id session:V00uVpEjVor)
  (timeStamp 2018-09-13T16:02:16.163)
  (NBestInd 3)
  (utterance "adicionar laranja esquerda")
  (targetFormula (call wallToString (call context:stackOnTop (call leftMost1 (call context:getNonEmpty)) (number 3 COLOR))))
  (targetValue (string [[0,2,1,3],[0,2,1],[0,2],[0]]))
)
