(example
  (id session:wzdsXQ32yYY)
  (context (date 2018 5 29) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3],[2],[1],[3]]) (name b) (name c))))
  (timeStamp 2018-06-29T16:46:19.784)
  (NBestInd 6)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 2 COLOR)))))
  (targetValue (string [[0],[1],[],[3],[],[1],[3]]))
)
(example
  (id session:wzdsXQ32yYY)
  (context (date 2018 5 29) (graph NaiveKnowledgeGraph ((string [[0],[1],[2],[3],[2],[1],[3]]) (name b) (name c))))
  (timeStamp 2018-06-29T16:46:32.792)
  (NBestInd 15)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[0],[1],[2],[],[2],[1],[]]))
)
(example
  (id session:wzdsXQ32yYY)
  (context (date 2018 5 29) (graph NaiveKnowledgeGraph ((string [[3],[0],[1],[0],[0]]) (name b) (name c))))
  (timeStamp 2018-06-29T16:46:39.520)
  (NBestInd 0)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[],[0],[1],[0],[0]]))
)
