(example (learningMode Explicit) (id session:XT429ROJOeT) (timeStamp 2018-09-14T10:29:27.115) (NBestInd 0) (utterance laranja))
(example
  (learningMode Implicit)
  (id session:XT429ROJOeT)
  (timeStamp 2018-09-14T10:29:57.840)
  (NBestInd 5)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
(example
  (learningMode Implicit)
  (id session:XT429ROJOeT)
  (timeStamp 2018-09-14T10:30:01.445)
  (NBestInd 0)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[1],[],[1],[0],[0],[1],[0]]))
)
(example
  (learningMode Implicit)
  (id session:XT429ROJOeT)
  (timeStamp 2018-09-14T10:30:07.642)
  (NBestInd 7)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[1],[],[3],[3],[2],[]]))
)
(example
  (learningMode Implicit)
  (id session:XT429ROJOeT)
  (timeStamp 2018-09-14T10:30:29.304)
  (NBestInd 4)
  (utterance "adicionar vermelho esquerda")
  (targetFormula (call wallToString (call context:stackOnTop (call leftMost1 (call context:getNonEmpty)) (number 2 COLOR))))
  (targetValue (string [[1,2],[2],[2],[1],[2]]))
)
(example (learningMode Explicit) (id session:XT429ROJOeT) (timeStamp 2018-09-14T10:30:43.805) (NBestInd 0) (utterance azul))
(example
  (learningMode Implicit)
  (id session:XT429ROJOeT)
  (timeStamp 2018-09-14T10:30:53.651)
  (NBestInd 0)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[],[],[],[2],[]]))
)
(example
  (learningMode Implicit)
  (id session:XT429ROJOeT)
  (timeStamp 2018-09-14T10:30:57.962)
  (NBestInd 0)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[1],[],[1],[],[1],[]]))
)
(example
  (learningMode Implicit)
  (id session:XT429ROJOeT)
  (timeStamp 2018-09-14T10:31:27.611)
  (NBestInd 6)
  (utterance "adicionar laranja castanho")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 1 COLOR)) (number 3 COLOR))))
  (targetValue (string [[3],[1,3],[1,3],[3]]))
)
(example
  (learningMode Active)
  (id session:XT429ROJOeT)
  (timeStamp 2018-09-14T10:31:31.221)
  (NBestInd 0)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[3],[2],[2],[],[0],[3],[]]))
)
(example
  (learningMode Implicit)
  (id session:XT429ROJOeT)
  (timeStamp 2018-09-14T15:46:29.588)
  (NBestInd 38)
  (utterance "dsf sdfm")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 0 COLOR)) (number 0 COLOR))))
  (targetValue (string [[2],[2],[0,0],[2],[0,0]]))
)
