(example
  (learningMode Implicit)
  (id session:XtSi2IkqhSv)
  (timeStamp 2018-09-14T16:00:20.436)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (learningMode Implicit)
  (id session:XtSi2IkqhSv)
  (timeStamp 2018-09-14T16:00:25.437)
  (NBestInd 24)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[2],[],[1],[2],[2]]))
)
(example
  (learningMode Implicit)
  (id session:XtSi2IkqhSv)
  (timeStamp 2018-09-14T16:00:30.440)
  (NBestInd 18)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
(example
  (learningMode Implicit)
  (id session:XtSi2IkqhSv)
  (timeStamp 2018-10-12T16:33:23.488)
  (NBestInd 38)
  (utterance "klkl lkkk")
  (targetFormula (call wallToString (call context:stackOnTop (call context:getTopColor (number 0 COLOR)) (number 0 COLOR))))
  (targetValue (string [[2],[2],[0,0],[2],[0,0]]))
)
