(example
  (learningMode Implicit)
  (id session:Z8cFqdB2FqH)
  (timeStamp 2018-09-13T15:58:35.991)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (learningMode Implicit)
  (id session:Z8cFqdB2FqH)
  (timeStamp 2018-09-13T15:59:13.748)
  (NBestInd 24)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[2],[],[1],[2],[2]]))
)
(example
  (learningMode Implicit)
  (id session:Z8cFqdB2FqH)
  (timeStamp 2018-09-13T15:59:21.083)
  (NBestInd 18)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
(example
  (learningMode Active)
  (id session:Z8cFqdB2FqH)
  (timeStamp 2018-09-13T15:59:28.411)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[3],[2],[1],[1],[1],[1],[]]))
)
