(example
  (id session:ZyeT94pvuho)
  (context (date 2018 6 3) (graph NaiveKnowledgeGraph ((string [[0],[3],[2],[3],[3],[3],[3]]) (name b) (name c))))
  (timeStamp 2018-07-03T08:36:46.049)
  (NBestInd 2)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getNonEmpty)))))
  (targetValue (string [[],[3],[2],[3],[3],[3],[3]]))
)
(example
  (id session:ZyeT94pvuho)
  (context (date 2018 6 3) (graph NaiveKnowledgeGraph ((string [[2],[3],[1],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-07-03T08:36:55.287)
  (NBestInd 24)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call leftMost1 (call context:getTopColor (number 3 COLOR))))))
  (targetValue (string [[2],[],[1],[2],[2]]))
)
(example
  (id session:ZyeT94pvuho)
  (context (date 2018 6 3) (graph NaiveKnowledgeGraph ((string [[2],[0],[0],[1],[1]]) (name b) (name c))))
  (timeStamp 2018-07-03T08:37:03.896)
  (NBestInd 18)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[0],[0],[],[]]))
)
(example
  (id session:ZyeT94pvuho)
  (context (date 2018 6 3) (graph NaiveKnowledgeGraph ((string [[1],[0],[3],[3],[2],[0]]) (name b) (name c))))
  (timeStamp 2018-07-03T08:37:13.042)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[1],[],[3],[3],[2],[]]))
)
(example
  (id session:ZyeT94pvuho)
  (context (date 2018 6 3) (graph NaiveKnowledgeGraph ((string [[3],[0],[1],[0],[3],[1]]) (name b) (name c))))
  (timeStamp 2018-07-03T08:37:24.606)
  (NBestInd 0)
  (utterance "apagar azul")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 0 COLOR)))))
  (targetValue (string [[3],[],[1],[],[3],[1]]))
)
(example
  (id session:ZyeT94pvuho)
  (context (date 2018 6 3) (graph NaiveKnowledgeGraph ((string [[2],[3],[2],[2],[2],[1],[3]]) (name b) (name c))))
  (timeStamp 2018-07-03T08:37:32.174)
  (NBestInd 0)
  (utterance "apagar castanho")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 1 COLOR)))))
  (targetValue (string [[2],[3],[2],[2],[2],[],[3]]))
)
(example
  (id session:ZyeT94pvuho)
  (context (date 2018 6 3) (graph NaiveKnowledgeGraph ((string [[2],[0],[1],[1],[2],[3],[0]]) (name b) (name c))))
  (timeStamp 2018-07-03T08:37:36.211)
  (NBestInd 0)
  (utterance "apagar laranja")
  (targetFormula (call wallToString (call context:removeTop (call context:getTopColor (number 3 COLOR)))))
  (targetValue (string [[2],[0],[1],[1],[2],[],[0]]))
)
(example
  (id session:ZyeT94pvuho)
  (context (date 2018 6 3) (graph NaiveKnowledgeGraph ((string [[0],[2],[0],[2]]) (name b) (name c))))
  (timeStamp 2018-07-03T08:37:56.349)
  (NBestInd 23)
  (utterance "apagar direita")
  (targetFormula (call wallToString (call context:removeTop (call rightMost1 (call context:getTopColor (number 2 COLOR))))))
  (targetValue (string [[0],[2],[0],[]]))
)
(example
  (id session:ZyeT94pvuho)
  (context (date 2018 6 3) (graph NaiveKnowledgeGraph ((string [[1],[1],[2],[1],[2],[2]]) (name b) (name c))))
  (timeStamp 2018-07-03T08:38:07.913)
  (NBestInd 13)
  (utterance "adicionar vermelho esquerda")
  (targetFormula (call wallToString (call context:stackOnTop (call leftMost1 (call context:getTopColor (number 1 COLOR))) (number 2 COLOR))))
  (targetValue (string [[1,2],[1],[2],[1],[2],[2]]))
)
